from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

import pytest


pytestmark = pytest.mark.contract

ROOT = Path(__file__).resolve().parents[2]
TAURI_ROOT = ROOT / "tobkiri_launcher" / "src-tauri"
TAURI_CONFIG = TAURI_ROOT / "tauri.conf.json"
SHELL_TAURI_CONFIG = TAURI_ROOT / "tauri.shell.conf.json"
SHELL_RUNTIME = TAURI_ROOT / "src" / "shell_runtime.rs"
LAUNCHER_RUNTIME = TAURI_ROOT / "src" / "lib.rs"
RESOURCE_PREPARER = ROOT / ".github" / "scripts" / "prepare_tauri_resources.py"
TOOLCHAIN_BINDER = ROOT / ".github" / "scripts" / "packaging_toolchain_identity.py"
LOCKED_TEST_HELPER = ROOT / ".github" / "scripts" / "install_locked_python_test_dependencies.py"
PACK_SHELL_SEALER = ROOT / ".github" / "scripts" / "seal_pack_shell.py"
UPDATER = TAURI_ROOT / "src" / "updater.rs"
RELEASE_WORKFLOW = ROOT / ".github" / "workflows" / "release.yml"
BUILD_AND_SIGN = ROOT / "scripts" / "build-and-sign.sh"
MACOS_CONFIG = TAURI_ROOT / "tauri.macos.conf.json"
MACOS_DEV_CONFIG = TAURI_ROOT / "tauri.macos.dev.conf.json"
MACOS_RELEASE_VERIFIER = ROOT / "tobkiri_launcher" / "scripts" / "verify_macos_release.sh"
MACOS_DMG_PACKAGER = ROOT / "tobkiri_launcher" / "scripts" / "package_macos_dmg.sh"
MACOS_DMG_CLEANUP = (
    ROOT / "tobkiri_launcher" / "scripts" / "cleanup_macos_dmg_workspace.py"
)
MACOS_DMG_PUBLISHER = (
    ROOT / "tobkiri_launcher" / "scripts" / "publish_macos_dmg.py"
)
MACOS_DMG_VERIFIER = (
    ROOT / "tobkiri_launcher" / "scripts" / "verify_packaged_python_dmg.py"
)
RELEASE_GATE = ROOT / "scripts" / "release_gate.py"
TEST_WORKFLOW = ROOT / ".github" / "workflows" / "test.yml"
PACKAGED_GENERATOR = (
    ROOT / "tobkiri_runtime" / "scripts" / "generate_packaged_defaultspack_v4_bundle.py"
)
PACKAGING_SOURCE_MANIFEST = (
    ROOT / "tobkiri_runtime" / "scripts" / "generator_source_manifest.py"
)
PACKAGING_CLEANUP = ROOT / "tobkiri_runtime" / "scripts" / "packaging_cleanup.py"
DEV_REQUIREMENTS = ROOT / "tobkiri_runtime" / "requirements-dev.txt"
DEV_PYPROJECT = ROOT / "tobkiri_runtime" / "pyproject.toml"
VIEWER_BUILD_WORKFLOWS = (
    ROOT / ".github" / "workflows" / "desktop-installers.yml",
    ROOT / ".github" / "workflows" / "release.yml",
)
BUILD_RS = TAURI_ROOT / "build.rs"
STARTUP_SPLASH = TAURI_ROOT / "splash" / "index.html"
STARTUP_PROGRESS_CAPABILITY = TAURI_ROOT / "capabilities" / "startup-progress.json"
STARTUP_PROGRESS_PERMISSION = (
    TAURI_ROOT / "permissions" / "autogenerated" / "get_setup_progress.toml"
)
PLATFORM_TARGETS = {
    "windows": ["nsis"],
    "macos": ["dmg"],
    "linux": ["deb", "appimage"],
}


def _load_resource_preparer():
    spec = importlib.util.spec_from_file_location("prepare_tauri_resources", RESOURCE_PREPARER)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {RESOURCE_PREPARER}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def test_tauri_hooks_prepare_runtime_for_dev_and_release():
    config = _read_json(TAURI_CONFIG)

    assert (
        "tobkiri_launcher/scripts/prepare_viewer_runtime.py --mode dev"
        in config["build"]["beforeDevCommand"]
    )
    assert (
        "tobkiri_launcher/scripts/prepare_viewer_runtime.py --mode release"
        in config["build"]["beforeBuildCommand"]
    )


def test_local_startup_splash_has_progress_authority_and_visible_failures():
    build_source = BUILD_RS.read_text(encoding="utf-8")
    capability = _read_json(STARTUP_PROGRESS_CAPABILITY)
    splash = STARTUP_SPLASH.read_text(encoding="utf-8")
    permission = STARTUP_PROGRESS_PERMISSION.read_text(encoding="utf-8")

    assert '"get_setup_progress"' in build_source
    assert capability["windows"] == ["main"]
    assert capability["permissions"] == ["allow-get-setup-progress"]
    assert "remote" not in capability
    assert 'commands.allow = ["get_setup_progress"]' in permission
    assert "Launcher progress unavailable. Retrying…" in splash
    assert ".catch(function () {})" not in splash


def test_shell_runtime_is_presentation_only_and_cannot_inherit_launcher_authority():
    shell_config = _read_json(SHELL_TAURI_CONFIG)
    assert shell_config["identifier"] == "io.tobkiri.shell.tauri"
    assert shell_config["mainBinaryName"] == "tobkiri-shell"
    assert shell_config["app"]["withGlobalTauri"] is False
    assert shell_config["app"]["trayIcon"] is None
    assert shell_config["bundle"]["resources"] is None
    assert shell_config["build"]["beforeBuildCommand"] is None
    assert shell_config["build"]["beforeDevCommand"] is None

    shell_runtime = SHELL_RUNTIME.read_text(encoding="utf-8")
    for forbidden in (
        "HostBrokerRuntime",
        "KernelManager",
        "DefaultspackManager",
        "invoke_handler",
        "tray::",
    ):
        assert forbidden not in shell_runtime
    assert "consume_shell_handoff" in shell_runtime
    assert "navigation_is_allowed" in shell_runtime

    launcher_runtime = LAUNCHER_RUNTIME.read_text(encoding="utf-8")
    assert "context.config().identifier == shell_handoff::SHELL_BUNDLE_IDENTIFIER" in launcher_runtime
    assert "shell_runtime::run(context)" in launcher_runtime
    assert "run_launcher(context)" in launcher_runtime


def test_installer_targets_are_selected_by_tauri_platform_overrides():
    base_config = _read_json(TAURI_CONFIG)
    assert base_config["bundle"]["targets"] == []

    for platform_name, expected_targets in PLATFORM_TARGETS.items():
        platform_config = _read_json(
            TAURI_ROOT / f"tauri.{platform_name}.conf.json"
        )
        targets = platform_config["bundle"]["targets"]
        assert targets == expected_targets
        assert "msi" not in targets


def test_ci_uses_tauri_as_the_single_release_preparation_entrypoint():
    for workflow in VIEWER_BUILD_WORKFLOWS:
        contents = workflow.read_text(encoding="utf-8")
        build_contents = contents.split("\n  gather:", 1)[0]
        assert "cargo tauri build" in build_contents
        assert "Prepare bundled Rumi runtime" not in build_contents
        assert "python .github/scripts/prepare_tauri_resources.py" not in build_contents
        rootless_at = build_contents.index("Build rootless sealed packaging Python")
        source_at = build_contents.index("Resolve checked-out source revision")
        assert rootless_at < source_at
        cargo_positions = [
            match.start() for match in re.finditer(r"cargo tauri build", build_contents)
        ]
        assert cargo_positions and all(position > source_at for position in cargo_positions)
        clean_at = build_contents.index("source_clean = subprocess.run(")
        untracked_at = build_contents.index('"ls-files"')
        output_at = build_contents.index('output.write(f"source_revision=')
        assert source_at < clean_at < output_at
        assert source_at < untracked_at < output_at
        assert '"diff-index"' in build_contents
        assert '"--cached"' in build_contents
        assert '"--no-ext-diff"' in build_contents
        assert '"--no-textconv"' in build_contents
        assert 'raise SystemExit("checked-out index must match HEAD")' in build_contents
        assert 'raise SystemExit("checked-out source has untracked paths")' in build_contents
        assert "TOBKIRI_PACKAGING_PYTHON" in build_contents
        assert "TOBKIRI_PACKAGING_PYTHON_SHA256" in build_contents
        assert "TOBKIRI_PACKAGING_GIT" in build_contents
        assert "TOBKIRI_PACKAGING_GIT_SHA256" in build_contents
        assert 'cat-file blob "$identity_oid" > "$identity_launcher"' in build_contents
        assert 'hash-object "$identity_launcher"' in build_contents
        assert "formal_identity() {" in build_contents
        assert 'exec 9< "$identity_launcher"' in build_contents
        stdin_invocation = (
            'PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -I -B - "$@" <&9'
        )
        assert stdin_invocation in build_contents
        assert 'IFS= read -r -n 1 <&9' in build_contents
        assert 'exec 9<&-' in build_contents
        assert "exec {identity_fd}" not in build_contents
        assert "/dev/fd" not in build_contents
        assert "eval " not in build_contents
        assert not any(
            line.strip().startswith(("source ", ". "))
            for line in build_contents.splitlines()
        )
        assert build_contents.count('exec 9< "$identity_launcher"') == 1
        assert build_contents.count(stdin_invocation) == 1
        assert build_contents.count("exec 9<&-") == 1
        assert build_contents.count("formal_identity ") == 4
        for invocation in (
            'formal_identity "$pre_git_env"',
            'formal_identity "-"',
            'formal_identity "$source_env"',
            'formal_identity "$TOOLCHAIN_ENV"',
        ):
            assert build_contents.count(invocation) == 1
        assert 'test "$identity_status" -eq 0' in build_contents
        assert 'test -s "$required_output"' in build_contents
        assert 'test -s "$identity_launcher"' in build_contents
        lines = build_contents.splitlines()
        open_line = next(
            index
            for index, line in enumerate(lines)
            if line.strip() == 'exec 9< "$identity_launcher"'
        )
        invocation_line = next(
            index for index, line in enumerate(lines) if stdin_invocation in line
        )
        close_line = next(
            index
            for index, line in enumerate(lines[invocation_line:], invocation_line)
            if line.strip() == "exec 9<&-"
        )
        assert invocation_line == open_line + 1
        assert close_line > invocation_line
        assert "source_revision=" in build_contents
        assert "source_tree=" in build_contents
        assert "TOBKIRI_PACKAGING_SOURCE_PROVENANCE_FILE" not in build_contents
        assert "--source-provenance-file" not in build_contents
        assert (
            '/usr/bin/python3 -B "$source_snapshot/.github/scripts/'
            "prepare_tauri_resources.py\""
        ) in build_contents
        assert (
            "--provenance .github/toolchains/packaging-python-macos.v1.json"
            in build_contents
        )
        assert build_contents.count('--source-commit "$GITHUB_SHA"') == 2
        assert (
            "--snapshot-source"
            in build_contents
        )
        assert "--source-tree" in build_contents
        assert "--prepare-macos-installation" not in build_contents
        assert "--source-clean" not in build_contents
        assert 'PYTHONDONTWRITEBYTECODE: "1"' in contents
        assert "aarch64-apple-darwin" in build_contents
        # Intel is deliberately outside the formal publication matrix; direct
        # Intel publication must fail closed.
        assert "x86_64-apple-darwin" not in build_contents
        for forbidden in (
            "windows-latest",
            "ubuntu-latest",
            "x86_64-pc-windows-msvc",
            "x86_64-unknown-linux-gnu",
            "Upload Windows",
            "Upload Linux",
            "Sign and verify Windows installer",
        ):
            assert forbidden not in build_contents


def test_python_generator_requires_snapshot_provenance_and_never_uses_git():
    """The relocated generator must use only formal snapshot provenance."""
    generator = PACKAGED_GENERATOR.read_text(encoding="utf-8")
    assert "subprocess" not in generator
    assert "_run_bound_git" not in generator
    assert "_verify_bound_git" not in generator
    assert "TOBKIRI_PACKAGING_GIT" not in generator
    assert "--source-provenance-file" in generator
    assert "_preverified_source_provenance" in generator
    assert "load_source_provenance" in generator
    for marker in (
        "--source-commit",
        "--source-tree",
        "--source-clean",
        "_preverified_source_commit",
        "_sealed_snapshot_root",
    ):
        assert marker not in generator

    source_manifest = PACKAGING_SOURCE_MANIFEST.read_text(encoding="utf-8")
    assert 'SOURCE_PROVENANCE_FILENAME = "packaging-source-provenance.v1.json"' in source_manifest

    cleanup = PACKAGING_CLEANUP.read_text(encoding="utf-8")
    isolated_keys = cleanup.split("_ISOLATED_ENVIRONMENT_KEYS", 1)[1].split(
        "_ISOLATED_MODULE_CODE", 1
    )[0]
    assert '"PATH"' not in isolated_keys


def test_packaging_test_jobs_disable_bytecode_and_locked_installs_do_not_compile():
    """Every packaging/test workflow and the locked helper keep closure trees source-only."""
    for workflow in (*VIEWER_BUILD_WORKFLOWS, TEST_WORKFLOW):
        assert 'PYTHONDONTWRITEBYTECODE: "1"' in workflow.read_text(encoding="utf-8")
    helper = LOCKED_TEST_HELPER.read_text(encoding="utf-8")
    assert '"--no-compile"' in helper
    assert 'environment["PYTHONDONTWRITEBYTECODE"] = "1"' in helper


def test_rust_packaging_callers_require_formal_absolute_tool_identities():
    """Rust release/build callers cannot fall back to ambient tools."""
    build = BUILD_RS.read_text(encoding="utf-8")
    assert TOOLCHAIN_BINDER.is_file()
    assert "packaged_source.rs" in build
    assert "packaging_toolchain.rs" in build
    assert 'packaging_toolchain::verified_tool("python")' in build
    assert 'packaging_toolchain::verified_tool("git")' in build
    assert "packaged_source::verify_and_snapshot_against_manifest" in build
    assert "trusted Rust source verification failed" in build
    assert 'Command::new("git")' not in build
    assert 'var_os("PYTHON")' not in build
    assert 'unwrap_or_else(|| "python"' not in build


def test_full_ci_macos_launcher_binds_git_before_rust_build():
    """The full macOS viewer build must snapshot a clean packaging source."""
    workflow = TEST_WORKFLOW.read_text(encoding="utf-8")
    macos_job = workflow.split("\n  tobkiri-launcher-macos:", 1)[1].split(
        "\n  mac-computer-driver-smoke:", 1
    )[0]
    binding_at = macos_job.index(
        "- name: Build rootless sealed packaging Python for viewer build"
    )
    setup_at = macos_job.index("- name: Set up Python")
    test_at = macos_job.index("- name: Run rumi viewer tests")
    assert binding_at < setup_at < test_at
    binding = macos_job[binding_at:setup_at]
    assert '--snapshot-source --snapshot-root "$source_snapshot"' in binding
    assert '--bind-git-env --env-output "$TOOLCHAIN_ENV"' in binding
    assert '/bin/cat "$TOOLCHAIN_ENV" >> "$GITHUB_ENV"' in binding
    assert '--target "$TOBKIRI_RUST_HOST_TARGET"' in binding
    rust_checks = macos_job[setup_at:]
    assert "- name: Build rumi viewer" not in rust_checks
    assert "run: cargo test --locked" in rust_checks


def test_macos_installer_uses_finder_free_verified_dmg_packager():
    assert MACOS_DMG_PACKAGER.is_file()
    packager = MACOS_DMG_PACKAGER.read_text(encoding="utf-8")
    for required in (
        "codesign --verify --strict --all-architectures",
        "Contents/MacOS/tobkiri-packvm-vz-helper",
        "dev.tobkiri.launcher.packvm-vz-helper",
        "ditto",
        "command -v plutil",
        "ln -s /Applications",
        "hdiutil create",
        "hdiutil info",
        "hdiutil detach",
        "-fs APFS",
        "-format UDZO",
        "cleanup_macos_dmg_workspace.py",
        "workspace_identity",
        '--device "$work_device"',
        "owned_image_paths",
        'create_stderr="$work_dir/hdiutil-create.stderr"',
        '"$temporary_dmg_path" 2>"$create_stderr"',
        "create_status=$?",
        'replay_stderr "$create_stderr"',
        'exit "$create_status"',
        "TOBKIRI_PACKAGING_PYTHON_SHA256",
        'trap \'cleanup "$?"\' EXIT',
        "trap 'exit 130' INT",
        "trap 'exit 143' TERM",
        "publish_macos_dmg.py",
        "verify_bound_image",
        "unsafe version for a DMG filename",
    ):
        assert required in packager
    assert "codesign --verify --deep" not in packager
    assert packager.count("hdiutil create") == 1
    assert packager.count('replay_stderr "$create_stderr"') == 2
    packager_lower = packager.lower()
    for forbidden in (
        "create_attempts", "create_attempt", "resource busy", "resource-busy",
        "resource_busy", "ebusy", "sleep", "retry",
    ):
        assert forbidden not in packager_lower
    assert MACOS_DMG_CLEANUP.is_file()
    assert MACOS_DMG_VERIFIER.is_file()
    mounted_verifier = MACOS_DMG_VERIFIER.read_text(encoding="utf-8")
    for required in (
        "O_DIRECTORY",
        "O_NOFOLLOW",
        "O_CLOEXEC",
        "device_metadata.st_rdev != metadata.st_dev",
        'self.hdiutil, ["detach", os.fspath(self.device)]',
        "verify_packaged_python.py",
        'codesign = _resolve_executable("codesign")',
        'python = _bind_executable(Path(sys.executable), "verification Python")',
    ):
        assert required in mounted_verifier
    mounted_shell = (
        ROOT / "tobkiri_launcher" / "scripts" / "verify_packaged_python_dmg.sh"
    ).read_text(encoding="utf-8")
    assert "verify_packaged_python_dmg.py" in mounted_shell
    assert "mktemp" not in mounted_shell
    assert "hdiutil detach" not in mounted_shell
    assert "-ov" not in packager
    assert "osascript" not in packager
    assert "bundle_dmg.sh" not in packager


def test_package_macos_dmg_retains_identity_verification_without_guard_attach():
    """The detached create result is bound and retained verification stays intact."""
    packager = MACOS_DMG_PACKAGER.read_text(encoding="utf-8")
    assert '-size "${minimum_dmg_size_kib}k"' not in packager
    assert "minimum_dmg_size_bytes" not in packager
    assert "bound_image_metadata()" in packager
    assert "os.O_NOFOLLOW" in packager
    assert packager.count("os.O_NONBLOCK") == 2
    assert "os.fstat(descriptor)" in packager
    assert "hdiutil attach" not in packager
    helper_start = packager.index("verify_bound_image() {")
    helper_end = packager.index("\nfind_exact_device() {", helper_start)
    helper = packager[helper_start:helper_end]
    assert '["hdiutil", "verify", f"/dev/fd/{descriptor}"]' in helper
    assert "pass_fds=(descriptor,)" in helper
    assert "identity changed during retained verification" in helper
    bind_index = packager.index('detached_image_identity=$(bound_image_metadata')
    identity_index = packager.index('current_id=$(image_identity "$temporary_dmg_path")', bind_index)
    verify_index = packager.index(
        'if ! verify_bound_image "$temporary_dmg_path" "$detached_image_identity"; then',
        identity_index,
    )
    publish_index = packager.index(
        'publish_verified_dmg "$temporary_dmg_path" "$detached_image_identity"',
        verify_index,
    )
    assert bind_index < identity_index < verify_index < publish_index
    assert '[[ -s "$temporary_dmg_path" ]]' in packager
    assert MACOS_DMG_PUBLISHER.is_file()
    publisher = MACOS_DMG_PUBLISHER.read_text(encoding="utf-8")
    assert "renameatx_np" in publisher
    assert "RENAME_EXCL" in publisher
    assert "renameat2" in publisher
    assert "RENAME_NOREPLACE" in publisher
    assert "_validate_regular_image(os.fstat(destination_descriptor)" in publisher

    desktop_workflow = (
        ROOT / ".github" / "workflows" / "desktop-installers.yml"
    ).read_text(encoding="utf-8")
    desktop_macos = desktop_workflow[
        desktop_workflow.index(
            "Build non-publishable macOS CI/E2E application"
        ) :
    ]
    assert "--bundles app" in desktop_macos
    assert "scripts/package_macos_dmg.sh" in desktop_macos
    assert "2>&1 | tee" in desktop_macos
    assert "--target '${{ matrix.target }}'" in desktop_macos
    assert "--ci-e2e-cert-sha256" in desktop_macos
    assert "TOBKIRI_MACOS_ARTIFACT_POLICY=ci-e2e-v1" in desktop_workflow
    for forbidden in (
        "--allow-ad-hoc-local",
        "add-trusted-cert",
        "create-keychain",
        "set-key-partition-list",
        "security ",
        "APPLE_CERTIFICATE",
        "APPLE_SIGNING_IDENTITY",
        "APPLE_TEAM_ID",
        "Developer ID",
        "notarytool",
        "stapler",
        "spctl",
        "softprops/action-gh-release",
        "Upload one reviewable draft release",
    ):
        assert forbidden not in desktop_workflow

    release_workflow = (ROOT / ".github" / "workflows" / "release.yml").read_text(
        encoding="utf-8"
    )
    release_macos = release_workflow[
        release_workflow.index("Build signed macOS application") :
    ]
    assert "--bundles app" in release_macos
    assert "scripts/package_macos_dmg.sh" in release_macos
    assert "2>&1 | tee" in release_macos

    for workflow in (desktop_workflow, release_workflow):
        assert "Capture macOS installer diagnostics" in workflow
        assert "hdiutil info || true" in workflow


def test_packaged_python_smoke_is_post_sign_read_only_in_both_workflows():
    """Native role smoke cannot leave mutable resources or break signing."""
    for workflow_path in VIEWER_BUILD_WORKFLOWS:
        workflow = workflow_path.read_text(encoding="utf-8")
        smoke_at = workflow.index(
            "Host-seal and launch-test packaged Python application resources"
        )
        tail = workflow[smoke_at:]
        smoke_section = tail[: tail.index("Build macOS DMG installer")]
        assert "--native-smoke" in smoke_section
        assert "Contents/Resources/app/logs" in smoke_section
        assert (
            "/usr/bin/codesign --verify --strict --all-architectures" in tail
            or "scripts/verify_macos_release.sh" in tail
        )

    mounted = MACOS_DMG_VERIFIER.read_text(encoding="utf-8")
    assert mounted.index('"--native-smoke"') < mounted.index('"--verify"')


def test_debug_pack_shell_is_built_and_sealed_before_launcher_rust_checks():
    assert PACK_SHELL_SEALER.is_file()
    expectations = (
        (
            ROOT / ".github" / "workflows" / "desktop-installers.yml",
            "Build debug Pack Shell for viewer Rust tests",
            "Seal debug Pack Shell for viewer Rust tests",
            "Run rumi viewer Rust tests",
        ),
        (
            TEST_WORKFLOW,
            "Build debug Pack Shell for viewer Rust checks",
            "Seal debug Pack Shell for viewer Rust checks",
            "Run rumi viewer tests",
        ),
        (
            RELEASE_WORKFLOW,
            "Build debug Pack Shell for release Rust tests",
            "Seal debug Pack Shell for release Rust tests",
            "Run Rust release smoke tests",
        ),
    )
    for workflow, build_name, seal_name, test_name in expectations:
        contents = workflow.read_text(encoding="utf-8")
        build_at = contents.index(build_name)
        seal_at = contents.index(seal_name)
        test_at = contents.index(test_name)
        assert build_at < seal_at < test_at
        relevant = contents[build_at:test_at]
        assert "cargo build --locked --manifest-path pack-shell/Cargo.toml" in relevant
        assert "python .github/scripts/seal_pack_shell.py" in relevant
        assert "--profile debug" in relevant


def test_packaging_workflows_isolate_cargo_outputs_from_restored_bundle_caches():
    """Read-only packaged bundles from Rust caches cannot block a rebuild."""
    workflows = (
        (
            ROOT / ".github" / "workflows" / "desktop-installers.yml",
            "tobkiri_launcher/src-tauri/target/desktop-installers",
        ),
        (
            RELEASE_WORKFLOW,
            "tobkiri_launcher/src-tauri/target/release-workflow",
        ),
    )
    cached_bundle_roots = (
        "tobkiri_launcher/src-tauri/target/${{ matrix.target }}/release/bundle",
        "src-tauri/target/${{ matrix.target }}/release/bundle",
    )
    for workflow, isolated_target in workflows:
        contents = workflow.read_text(encoding="utf-8")
        assert (
            f"CARGO_TARGET_DIR: ${{{{ github.workspace }}}}/{isolated_target}"
            in contents
        )
        assert 'cache-targets: "false"' in contents
        assert 'bundle_dir="$CARGO_TARGET_DIR/' in contents
        for cached_root in cached_bundle_roots:
            assert cached_root not in contents


def test_release_pack_shell_rebuilds_from_empty_or_cached_targets_and_seals_both_profiles():
    contents = RELEASE_WORKFLOW.read_text(encoding="utf-8")
    clean_at = contents.index("Clean cached Pack Shell outputs before verified build")
    debug_build_at = contents.index("Build debug Pack Shell for release Rust tests")
    debug_seal_at = contents.index("Seal debug Pack Shell for release Rust tests")
    rust_test_at = contents.index("Run Rust release smoke tests")
    release_build_at = contents.index("Build release Pack Shell for verified Tauri Shell artifact")
    release_seal_at = contents.index("Seal release Pack Shell for verified Tauri Shell artifact")
    shell_build_at = contents.index("Build verified Tauri Shell artifact")

    assert clean_at < debug_build_at < debug_seal_at < rust_test_at
    assert rust_test_at < release_build_at < release_seal_at < shell_build_at
    assert "cargo clean --manifest-path pack-shell/Cargo.toml --target" in contents
    assert "cargo build --locked --manifest-path pack-shell/Cargo.toml" in contents
    assert "cargo build --release --locked --manifest-path pack-shell/Cargo.toml" in contents
    assert "--profile debug" in contents
    assert "--profile release" in contents
    assert "cache-hit" not in contents

    sealer = PACK_SHELL_SEALER.read_text(encoding="utf-8")
    preparer = RESOURCE_PREPARER.read_text(encoding="utf-8")
    assert "seal_pack_shell_binary" in sealer
    assert "pack_shell_digest_path" in preparer
    assert "hashlib.sha256(payload)" in preparer
    assert "sha256" in preparer


def test_updater_origin_matches_the_release_workflow_and_rejects_legacy_repository():
    updater = UPDATER.read_text(encoding="utf-8")
    workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")
    repository = re.search(
        r"TOBKIRI_RELEASE_REPOSITORY:\s*([^\s]+)", workflow
    )
    assert repository is not None
    assert repository.group(1) == "harupipipipi/tobkiri"
    assert 'RELEASE_REPOSITORY: &str = "harupipipipi/tobkiri"' in updater
    assert "https://api.github.com/repos/harupipipipi/tobkiri/releases/latest" in updater
    runtime_source = updater.split("#[cfg(test)]", 1)[0]
    assert "rumiai" not in runtime_source.lower()
    assert "repository=\"$(printf '%s' \"$GITHUB_REPOSITORY\" | tr '[:upper:]' '[:lower:]')\"" in workflow
    assert "expected=\"$(printf '%s' \"$TOBKIRI_RELEASE_REPOSITORY\" | tr '[:upper:]' '[:lower:]')\"" in workflow


def test_build_and_sign_rebuilds_canonical_defaultspack_before_staging():
    helper = BUILD_AND_SIGN.read_text(encoding="utf-8")
    build_at = helper.index("npm run build")
    check_at = helper.index("npm run check:shell-bundle")
    stage_at = helper.index("prepare_viewer_runtime.py")
    tauri_builds = [
        match.start() for match in re.finditer(r"cargo tauri build", helper)
    ]
    assert build_at < check_at < stage_at
    assert tauri_builds and all(position > stage_at for position in tauri_builds)
    assert "DEFAULTSPACK_WEBAPP_ROOT" in helper


def test_release_platform_signing_is_fail_closed_and_ad_hoc_is_dev_only():
    workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")
    release_gate = RELEASE_GATE.read_text(encoding="utf-8")
    verifier = MACOS_RELEASE_VERIFIER.read_text(encoding="utf-8")
    mac_config = _read_json(MACOS_CONFIG)
    dev_config = _read_json(MACOS_DEV_CONFIG)

    for required in (
        "APPLE_CERTIFICATE_BASE64",
        "APPLE_CERTIFICATE_PASSWORD",
        "APPLE_SIGNING_IDENTITY",
        "APPLE_ID",
        "APPLE_APP_SPECIFIC_PASSWORD",
        "APPLE_TEAM_ID",
        "scripts/release_gate.py sign-artifacts",
    ):
        assert required in workflow

    for required in (
        "signtool.exe",
        '"sign"',
        '"verify"',
        '"notarytool"',
        '"stapler"',
        '"spctl"',
        '"ditto"',
    ):
        assert required in release_gate

    for required in (
        "Developer ID Application: ",
        "codesign --verify --deep --strict",
        "codesign --display --verbose=4",
        "Authority=-",
    ):
        assert required in verifier

    assert mac_config["bundle"]["targets"] == ["dmg"]
    assert "signingIdentity" not in mac_config["bundle"].get("macOS", {})
    assert dev_config["bundle"]["macOS"]["signingIdentity"] == "-"
    assert "tauri.macos.dev.conf.json" not in workflow
    desktop_workflow = (
        ROOT / ".github" / "workflows" / "desktop-installers.yml"
    ).read_text(encoding="utf-8")
    assert "--config src-tauri/tauri.macos.dev.conf.json" in desktop_workflow
    assert "--ci-e2e-cert-sha256" in desktop_workflow
    for forbidden in (
        "--allow-ad-hoc-local",
        "add-trusted-cert",
        "create-keychain",
        "set-key-partition-list",
        "security ",
        "APPLE_CERTIFICATE",
        "APPLE_SIGNING_IDENTITY",
        "APPLE_TEAM_ID",
        "Developer ID",
        "softprops/action-gh-release",
        "Upload one reviewable draft release",
    ):
        assert forbidden not in desktop_workflow
    assert "--allow-ad-hoc-local" not in workflow
    assert "TOBKIRI_MACOS_ARTIFACT_POLICY" not in workflow
    assert "ci-e2e" not in workflow

    verify_at = workflow.index("Verify Developer ID signed macOS application")
    dmg_at = workflow.index("Build macOS DMG installer")
    notarize_at = workflow.index("Notarize and staple macOS release DMG")
    upload_at = workflow.index("Upload one reviewable draft release")
    assert verify_at < dmg_at < notarize_at < upload_at
    assert "WINDOWS_CERTIFICATE_BASE64" not in workflow
    assert "WINDOWS_CERTIFICATE_PASSWORD" not in workflow
    assert "Sign and verify Windows installer" not in workflow
    assert "Linux" not in workflow
    assert set(re.findall(r"(?:aarch64|x86_64)-apple-darwin", workflow)) == {
        "aarch64-apple-darwin"
    }


def test_pack_shell_profile_is_a_single_safe_path_component():
    preparer = _load_resource_preparer()
    preparer._validate_profile_component("debug")
    preparer._validate_profile_component("release")

    for invalid in ("", ".", "..", "../debug", "debug/child", "debug\\child"):
        with pytest.raises(ValueError):
            preparer._validate_profile_component(invalid)


def test_dev_uv_version_matches_release_bundle_pin():
    preparer = _load_resource_preparer()
    pinned_requirement = f"uv=={preparer.UV_PINNED_VERSION}"
    requirements = DEV_REQUIREMENTS.read_text(encoding="utf-8").splitlines()
    pyproject = DEV_PYPROJECT.read_text(encoding="utf-8")

    assert any(line.startswith(pinned_requirement) for line in requirements)
    assert f'"{pinned_requirement}"' in pyproject
