from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from domain.ui_compiler import CompositionManifest, PlannedNode, UIPlan, UICompilerArtifactStore

from .project_writer import write_json, write_text


class PageComposer:
    def __init__(self, *, store: UICompilerArtifactStore) -> None:
        self.store = store

    def compose(
        self,
        *,
        run_id: str,
        run_root: Path,
        plan: UIPlan,
        accepted_decisions: dict[str, Any],
        target: dict[str, Any] | None = None,
    ) -> CompositionManifest:
        target = target if isinstance(target, dict) else {}
        source_root = run_root / "composition" / "source"
        source_root.mkdir(parents=True, exist_ok=True)
        imports: list[dict[str, Any]] = []
        for contract in plan.contracts():
            decision = accepted_decisions.get(contract.id)
            accepted_candidate_id = getattr(decision, "accepted_candidate_id", None)
            if not accepted_candidate_id:
                raise ValueError(f"missing accepted bundle for {contract.id}")
            imports.append(
                {
                    "nodeId": contract.id,
                    "candidateId": accepted_candidate_id,
                    "importPath": f"../../accepted/{contract.id}/source/Component",
                }
            )
        slot_mappings = _slot_mappings(plan)
        render_tree = _render_tree(plan.root)
        write_text(source_root / "generated-index.ts", _generated_index(imports))
        write_text(source_root / "App.tsx", _app_source(slot_mappings, render_tree))
        write_json(
            source_root / "adapters" / "slot-mappings.json",
            {"slotMappings": slot_mappings, "target": target},
        )
        manifest = CompositionManifest(
            run_id=run_id,
            source_root=str(source_root),
            entry=str(target.get("entry") or "src/App.tsx"),
            imports=imports,
            slot_mappings=slot_mappings,
        )
        self.store.save_composition(
            run_id=run_id,
            manifest=manifest.to_dict(),
            report={
                "status": "composed",
                "leafSourceEdited": False,
                "imports": imports,
                "slotMappings": slot_mappings,
                "renderTree": _render_tree_data(plan.root),
            },
        )
        return manifest


def _slot_mappings(plan: UIPlan) -> list[dict[str, Any]]:
    mappings: list[dict[str, Any]] = []
    for contract in plan.contracts():
        for slot in contract.slots:
            if slot.accepts_node_id:
                mappings.append({"parentNodeId": contract.id, "slotId": slot.id, "nodeId": slot.accepts_node_id})
    return mappings


def _generated_index(imports: list[dict[str, Any]]) -> str:
    import_lines = ["// Generated by Rumi recursive UI compiler."]
    entries = ["export const rumiComponents = {"]
    for item in imports:
        symbol = _symbol(str(item["nodeId"]))
        import_lines.append(f"import {symbol} from '{item['importPath']}';")
        entries.append(f"  '{item['nodeId']}': {symbol},")
    entries.append("};")
    return "\n".join([*import_lines, "", *entries])


def _app_source(slot_mappings: list[dict[str, Any]], render_tree: str) -> str:
    return "\n".join(
        [
            "import type { ReactNode } from 'react';",
            "import { rumiComponents } from './generated-index';",
            "",
            "export default function App() {",
            f"  const slotMappings = {json.dumps(slot_mappings, ensure_ascii=False)};",
            "  const components = rumiComponents as Record<string, any>;",
            "  const renderNode = (nodeId: string, slotId: string | null, children: ReactNode[] = []) => {",
            "    const Component = components[nodeId];",
            "    if (!Component) return null;",
            "    return (",
            "      <Component key={nodeId} slotMappings={slotMappings} data-rumi-node={nodeId} data-rumi-slot={slotId || undefined}>",
            "        {children}",
            "      </Component>",
            "    );",
            "  };",
            "  return (",
            "    <main data-rumi-composition=\"recursive-ui\">",
            *["      " + line for line in _jsx_expression(render_tree)],
            "    </main>",
            "  );",
            "}",
        ]
    )


def _symbol(node_id: str) -> str:
    return "Component" + "".join(part.capitalize() for part in node_id.split("-"))


def _render_tree(node: PlannedNode, *, depth: int = 0, slot_id: str | None = None) -> str:
    child_sources = []
    for child in _ordered_children(node):
        child_slot_id = _slot_id_for_child(node, child)
        child_sources.append(_render_tree(child, depth=depth + 1, slot_id=child_slot_id))
    children = "\n".join(source + "," for source in child_sources if source.strip())
    indent = "  " * depth
    contract = node.contract
    if contract is None:
        return children
    slot_value = json.dumps(slot_id) if slot_id else "null"
    if children:
        return "\n".join(
            [
                f"{indent}renderNode({json.dumps(contract.id)}, {slot_value}, [",
                children,
                f"{indent}])",
            ]
        )
    return f"{indent}renderNode({json.dumps(contract.id)}, {slot_value})"


def _ordered_children(node: PlannedNode) -> list[PlannedNode]:
    if not node.children:
        return []
    slot_order = {
        slot.accepts_node_id: index
        for index, slot in enumerate(node.node.slots)
        if slot.accepts_node_id
    }
    return sorted(
        node.children,
        key=lambda child: (
            slot_order.get(child.node.id, len(slot_order)),
            child.node.id,
        ),
    )


def _slot_id_for_child(parent: PlannedNode, child: PlannedNode) -> str | None:
    for slot in parent.node.slots:
        if slot.accepts_node_id == child.node.id:
            return slot.id
    return None


def _render_tree_data(node: PlannedNode) -> dict[str, Any]:
    return {
        "nodeId": node.node.id,
        "contractId": node.contract.id if node.contract else None,
        "children": [_render_tree_data(child) for child in _ordered_children(node)],
    }


def _jsx_expression(expression: str) -> list[str]:
    lines = expression.splitlines() or ["null"]
    if len(lines) == 1:
        return ["{" + lines[0] + "}"]
    lines[0] = "{" + lines[0]
    lines[-1] = lines[-1] + "}"
    return lines
