"""Canonical Team organizational model and least-privilege policy resolver.

The Team model is deliberately independent from the legacy Company route.  A
Company compatibility projection may use these helpers, but this package does
not grant authority, execute tools, or select a provider.  It only validates
organizational state and freezes the policy that a separately owned
coordinator must enforce.
"""

from .model import (
    ASSIGNMENT_SCHEMA_VERSION,
    ASSIGNMENT_STATES,
    ATTEMPT_SCHEMA_VERSION,
    ATTEMPT_STATES,
    ASSURANCE_LEVELS,
    AVAILABILITY_STATES,
    CONFIGURATION_STATES,
    DEPARTMENT_SCHEMA_VERSION,
    DISPATCH_MODES,
    EFFECTIVE_POLICY_SCHEMA_VERSION,
    MEMBER_POOL_SCHEMA_VERSION,
    POLICY_SCHEMA_VERSION,
    PolicyResolution,
    TEAM_DEFINITION_SCHEMA_VERSION,
    TEAM_SCHEMA_VERSION,
    TEAM_STATES,
    TARGET_KINDS,
    REVIEW_LEVELS,
    AliasResolutionError,
    PolicyResolutionError,
    ProfileAdoptionError,
    SnapshotIntegrityError,
    TeamModelError,
    TeamValidationError,
    adopt_profile_revision,
    apply_materialization_plan,
    canonical_hash,
    can_accept_assignment,
    create_assignment,
    create_attempt,
    export_legacy_company,
    export_team,
    materialization_plan,
    materialize_team,
    migrate_legacy_company,
    normalize_policy,
    normalize_profile,
    normalize_team_definition,
    plan_profile_update,
    resolve_effective_policy,
    resolve_member_alias,
    settle_member_availability,
    team_console_snapshot,
    update_member_state,
    validate_policy_snapshot,
    validate_team_definition,
)

__all__ = [
    "ASSIGNMENT_SCHEMA_VERSION",
    "ASSIGNMENT_STATES",
    "ATTEMPT_SCHEMA_VERSION",
    "ATTEMPT_STATES",
    "ASSURANCE_LEVELS",
    "AVAILABILITY_STATES",
    "CONFIGURATION_STATES",
    "DEPARTMENT_SCHEMA_VERSION",
    "DISPATCH_MODES",
    "EFFECTIVE_POLICY_SCHEMA_VERSION",
    "MEMBER_POOL_SCHEMA_VERSION",
    "POLICY_SCHEMA_VERSION",
    "PolicyResolution",
    "REVIEW_LEVELS",
    "TARGET_KINDS",
    "TEAM_DEFINITION_SCHEMA_VERSION",
    "TEAM_SCHEMA_VERSION",
    "TEAM_STATES",
    "AliasResolutionError",
    "PolicyResolutionError",
    "ProfileAdoptionError",
    "SnapshotIntegrityError",
    "TeamModelError",
    "TeamValidationError",
    "adopt_profile_revision",
    "apply_materialization_plan",
    "canonical_hash",
    "can_accept_assignment",
    "create_assignment",
    "create_attempt",
    "export_legacy_company",
    "export_team",
    "materialization_plan",
    "materialize_team",
    "migrate_legacy_company",
    "normalize_policy",
    "normalize_profile",
    "normalize_team_definition",
    "plan_profile_update",
    "resolve_effective_policy",
    "resolve_member_alias",
    "settle_member_availability",
    "team_console_snapshot",
    "update_member_state",
    "validate_policy_snapshot",
    "validate_team_definition",
]
