"""
blocks/chat/history/replace_with_summary.py - Replace message range with AI summary.

Deletes all messages in the range and inserts a single summary message
generated by the AI at the same position.

Input:
    conversation_id: str (required)
    start_message_id: str (required)
    end_message_id: str (required)
    instruction: str (optional) - additional instruction for summarization
    model: str (optional) - override model for summarization

Returns:
    replacement_message, deleted_message_ids, deleted_count, conversation
"""

from blocks._common import ok, error

from domain.chat.store import ChatStore
from domain.chat.message_converter import convert_to_standard
from domain.chat.history_editor import replace_range_with_message
from blocks.chat.send import _ai_direct_complete
from blocks.chat._prompt_helpers import (
    build_summarize_prompt,
    extract_text,
)


def _build_summarize_prompt(standard_messages, instruction=None):
    """Build the AI prompt for summarizing a message range."""
    return build_summarize_prompt(
        standard_messages,
        instruction,
        persona="editor",
        user_prefix=(
            "Summarize the following conversation segment. "
            "Keep all important results and conclusions:"
        ),
    )


def _unavailable_summary(standard_messages):
    """Structured error used by legacy callers if AI summarization is unavailable."""
    return {
        "success": False,
        "error": "AI summarization is unavailable",
        "error_type": "not_implemented",
    }


def _extract_text(response):
    """Backwards-compatible alias for the shared extract_text helper."""
    return extract_text(response)


def run(input_data, context):
    store = ChatStore()

    conversation_id = input_data.get("conversation_id")
    if not conversation_id:
        return error("conversation_id is required", "INVALID_INPUT")

    start_message_id = input_data.get("start_message_id")
    if not start_message_id:
        return error("start_message_id is required", "INVALID_INPUT")

    end_message_id = input_data.get("end_message_id")
    if not end_message_id:
        return error("end_message_id is required", "INVALID_INPUT")

    conv = store.get_conversation(conversation_id)
    if conv is None:
        return error("Conversation not found", "NOT_FOUND")

    # --- Get range and convert for AI ---
    range_result = store.get_messages_range(
        conversation_id, start_message_id, end_message_id
    )
    if range_result is None:
        return error(
            "Invalid message range: start or end message not found",
            "INVALID_RANGE",
        )

    range_messages, start_idx = range_result
    if not range_messages:
        return error("No messages in specified range", "EMPTY_RANGE")

    if len(range_messages) < 2:
        return error(
            "At least 2 messages required for summarization",
            "RANGE_TOO_SMALL",
        )

    standard_messages = convert_to_standard(range_messages)
    instruction = input_data.get("instruction")
    model = input_data.get("model", "default")
    if model == "default":
        model = conv.get("model", "stub/default")

    summarize_prompt = _build_summarize_prompt(standard_messages, instruction)

    # --- Call AI for summary ---
    call_handler = context.get("call_handler") if context else None
    if call_handler is not None:
        try:
            ai_params = {
                "model": model,
                "messages": summarize_prompt,
                "tools": [],
                "params": {},
            }
            response = call_handler("defaults.ai.complete", ai_params)
        except Exception as exc:
            return error("AI request failed: " + str(exc), "AI_ERROR")
        if isinstance(response, dict) and response.get("status") == "error":
            err = response.get("error", {})
            message = err.get("message") if isinstance(err, dict) else None
            return error(str(message or "AI request failed"), "AI_ERROR")
        if isinstance(response, dict) and response.get("status") == "ok":
            response = response.get("data", {})
    else:
        response, ai_error = _ai_direct_complete(model, summarize_prompt, [], {})
        if ai_error is not None:
            return error(ai_error, "AI_ERROR")
    if not isinstance(response, dict):
        return error("AI provider returned an invalid response", "AI_ERROR")

    summary_text = _extract_text(response)

    # --- Build replacement message and execute ---
    summary_msg_dict = {
        "role": "assistant",
        "content": [{"type": "text", "text": summary_text}],
        "metadata": {
            "is_summary": True,
            "edit_type": "replace_with_summary",
            "original_message_count": len(range_messages),
            "original_message_ids": [m["id"] for m in range_messages],
            "summary_instruction": instruction,
        },
    }

    result, err = replace_range_with_message(
        store, conversation_id,
        start_message_id, end_message_id,
        summary_msg_dict,
    )
    if err is not None:
        return error(err, "INTERNAL_ERROR")

    return ok(result)
