from __future__ import annotations

from ..models import ConnectionProvider, OAuthConfig, ProviderCapability

CLOUDFLARE_PROVIDER = ConnectionProvider(
    provider_id="cloudflare",
    display_name="Cloudflare",
    description="Run cloud-capable sandbox work in the user's Cloudflare account and bridge PC-bound tools through a named Tunnel.",
    icon="cloudflare",
    service_kind="cloud",
    auth_type="oauth2",
    official_broker_supported=True,
    self_host_client_supported=True,
    auth_template="generic_oauth2_pkce",
    token_import_supported=True,
    priority=30,
    oauth=OAuthConfig(
        authorization_url="https://dash.cloudflare.com/oauth2/auth",
        token_url="https://dash.cloudflare.com/oauth2/token",
        revoke_url="https://dash.cloudflare.com/oauth2/revoke",
        userinfo_url="https://dash.cloudflare.com/oauth2/userinfo",
        default_scopes=[],
        pkce_supported=True,
        token_endpoint_auth_method="client_secret_post",
    ),
    capabilities=[
        ProviderCapability(
            id="cloudflare.account.read",
            display_name="Read account metadata",
            description="List/select the Cloudflare account Rumi should use.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.pages.project.read",
            display_name="Read Pages projects",
            description="List and inspect Cloudflare Pages projects.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.pages.project.write",
            display_name="Write Pages projects",
            description="Create, update, and delete Cloudflare Pages projects.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.pages.deployment.read",
            display_name="Read Pages deployments",
            description="List and inspect Cloudflare Pages deployments.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.pages.deployment.write",
            display_name="Write Pages deployments",
            description="Create and delete Cloudflare Pages deployments.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.worker.read",
            display_name="Read Workers",
            description="Inspect Cloudflare Worker resources.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.worker.write",
            display_name="Write Workers",
            description="Create or update Cloudflare Worker resources.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.r2.read",
            display_name="Read R2",
            description="Inspect Cloudflare R2 resources.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.r2.write",
            display_name="Write R2",
            description="Create or update Cloudflare R2 resources.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.d1.read",
            display_name="Read D1",
            description="Inspect Cloudflare D1 resources.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.d1.write",
            display_name="Write D1",
            description="Create or update Cloudflare D1 resources.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.queue.read",
            display_name="Read Queues",
            description="Inspect Cloudflare Queues resources.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.queue.write",
            display_name="Write Queues",
            description="Create or update Cloudflare Queues resources.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.workflow.read",
            display_name="Read Workflows",
            description="Inspect Cloudflare Workflows resources.",
            risk="low",
        ),
        ProviderCapability(
            id="cloudflare.workflow.write",
            display_name="Write Workflows",
            description="Create or update Cloudflare Workflows resources.",
            risk="high",
        ),
        ProviderCapability(
            id="cloudflare.runner.deploy",
            display_name="Deploy Rumi runner",
            description="Create or update Cloudflare Sandbox Bridge and PC Tool Bridge runner resources.",
            risk="high",
        ),
    ],
    scope_presets=[
        {"id": "account_read", "label": "Read account metadata", "scopes": ["account:read", "user:read"]},
    ],
    scope_to_capability=[
        {"credential_kinds": ["oauth2_token"], "capabilities": ["cloudflare.account.read"]},
        {"scopes": ["account:read"], "capabilities": ["cloudflare.account.read"]},
        {"scopes": ["pages:read"], "capabilities": ["cloudflare.pages.project.read", "cloudflare.pages.deployment.read"]},
        {
            "scopes": ["pages:write"],
            "capabilities": [
                "cloudflare.pages.project.read",
                "cloudflare.pages.project.write",
                "cloudflare.pages.deployment.read",
                "cloudflare.pages.deployment.write",
            ],
        },
        {"scopes": ["workers:read", "workers_scripts:read"], "capabilities": ["cloudflare.worker.read"]},
        {
            "scopes": ["workers:write", "workers_scripts:edit"],
            "capabilities": ["cloudflare.worker.read", "cloudflare.worker.write"],
        },
        {"scopes": ["d1:read"], "capabilities": ["cloudflare.d1.read"]},
        {"scopes": ["d1:write"], "capabilities": ["cloudflare.d1.read", "cloudflare.d1.write"]},
        {"scopes": ["r2:read"], "capabilities": ["cloudflare.r2.read"]},
        {"scopes": ["r2:write"], "capabilities": ["cloudflare.r2.read", "cloudflare.r2.write"]},
        {"scopes": ["queues:read"], "capabilities": ["cloudflare.queue.read"]},
        {
            "scopes": ["queues:write"],
            "capabilities": ["cloudflare.queue.read", "cloudflare.queue.write"],
        },
        {"scopes": ["workflows:read"], "capabilities": ["cloudflare.workflow.read"]},
        {
            "scopes": ["workflows:write"],
            "capabilities": ["cloudflare.workflow.read", "cloudflare.workflow.write"],
        },
        {
            "scopes": [
                "workers:write",
                "workers_scripts:edit",
                "pages:write",
                "d1:write",
                "r2:write",
                "queues:write",
                "workflows:write",
            ],
            "match": "all",
            "capabilities": ["cloudflare.runner.deploy"],
        },
    ],
    adapter={
        "python": "ecosystem.defaultspack.domain.connections.cloudflare:CloudflareConnectionAdapter",
        "sdk_optional": True,
    },
    metadata={
        "scope_selection": "Select exact OAuth scopes from Cloudflare OAuth client configuration/API for the minimum runner resources used by the implementation.",
        "oss_behavior": "If official broker is unavailable, show Download Official App and Configure self-host OAuth.",
        "sandbox_bridge_scaffold_path": "tobkiri_runtime/ecosystem/defaultspack/cloudflare/sandbox_bridge",
        "sandbox_bridge_runtime": "Cloudflare Sandbox Bridge HTTP API via @cloudflare/sandbox/bridge",
        "tool_coverage_surface": "/api/tools/catalog",
        "all_tools_cloudflare_native_supported": False,
        "pc_bridge_required_for_host_tools": True,
        "pc_tunnel_scaffold_path": "tobkiri_runtime/ecosystem/defaultspack/cloudflare/pc_tunnel",
        "pc_tool_bridge_scaffold_path": "tobkiri_runtime/ecosystem/defaultspack/cloudflare/pc_tool_bridge",
        "pc_tool_bridge_runtime": "Cloudflare Worker narrow proxy to a named Tunnel PC runtime",
        "stable_pc_tunnel_note": "Cloudflare Pages/pages.dev is not a permanent tunnel to a Mac. Use a named Cloudflare Tunnel plus a DNS hostname on a Cloudflare-managed zone.",
        "pc_tool_bridge_note": "PC-bound tools are not uploaded to Cloudflare. They are invoked through the PC Tool Bridge, preserving PC runtime approval, policy, and audit.",
        "free_plan_note": "Cloudflare Sandbox uses Cloudflare Containers. Accounts without Containers access require the Workers Paid plan.",
        "self_host_env": [
            "RUMI_CLOUDFLARE_OAUTH_CLIENT_ID",
            "RUMI_CLOUDFLARE_OAUTH_SCOPES",
            "RUMI_CLOUDFLARE_OAUTH_REDIRECT_URI",
            "RUMI_CLOUDFLARE_SANDBOX_BRIDGE_URL",
            "RUMI_CLOUDFLARE_SANDBOX_API_KEY",
            "RUMI_CLOUDFLARE_PC_TUNNEL_HOSTNAME",
            "RUMI_CLOUDFLARE_PC_TUNNEL_ORIGIN_URL",
            "RUMI_CLOUDFLARE_PC_TUNNEL_CONFIG",
            "RUMI_CLOUDFLARE_PC_TOOL_BRIDGE_URL",
            "RUMI_PC_TOOL_BRIDGE_TOKEN",
            "RUMI_PC_RUNTIME_BEARER",
            "RUMI_PC_ORIGIN",
            "RUMI_PC_TOOL_BRIDGE_ALLOWED_ORIGIN",
        ],
        "self_host_client_credential": "optional_env",
        "direct_token_env": [
            "RUMI_CLOUDFLARE_OAUTH_ACCESS_TOKEN",
            "RUMI_CLOUDFLARE_OAUTH_REFRESH_TOKEN",
            "CLOUDFLARE_API_TOKEN",
            "CF_API_TOKEN",
        ],
        "optional_context_env": [
            "RUMI_CLOUDFLARE_ACCOUNT_ID",
            "CLOUDFLARE_ACCOUNT_ID",
            "RUMI_CLOUDFLARE_ZONE_ID",
            "CLOUDFLARE_ZONE_ID",
        ],
    },
)
