"""Schema-driven Pack SDK generation and validation."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker

from .pack_boundary import finite_children
from tobkiri_protocol.canonical import canonical_digest
from tobkiri_protocol.errors import ProtocolError
from tobkiri_protocol.validation import validate_document


class PackSdkError(ValueError):
    """Raised when Pack SDK generation or validation fails."""


class PackSdkGenerator:
    """Generate deterministic language bindings from authoritative schemas."""

    def __init__(self, schema_paths: list[Path]) -> None:
        if not schema_paths:
            raise PackSdkError("at least one schema is required")
        self.schema_paths = [path.resolve() for path in schema_paths]

    def generate(self, output_dir: Path, *, check: bool = False) -> dict[str, str]:
        """Write generated SDK artifacts or verify that they have no drift."""

        artifacts = self.render()
        if check:
            actual = {
                entry.name
                for entry in os.scandir(output_dir)
                if entry.is_file() and entry.name != "command_inventory.json"
            } if output_dir.is_dir() else set()
            drift = [
                name
                for name, content in artifacts.items()
                if not (output_dir / name).is_file()
                or (output_dir / name).read_text(encoding="utf-8") != content
            ]
            drift.extend(sorted(actual - set(artifacts)))
            if drift:
                raise PackSdkError(
                    "generated SDK drift detected: " + ", ".join(sorted(drift))
                )
            return {name: _sha256_text(content) for name, content in artifacts.items()}

        output_dir.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(
            prefix=".pack-sdk-",
            dir=output_dir.parent,
        ) as temp_value:
            temp_dir = Path(temp_value)
            for name, content in artifacts.items():
                (temp_dir / name).write_text(content, encoding="utf-8")
            for entry in os.scandir(output_dir):
                existing = Path(entry.path)
                if (
                    entry.is_file()
                    and existing.name != "command_inventory.json"
                    and existing.name not in artifacts
                ):
                    existing.unlink()
            for name in artifacts:
                os.replace(temp_dir / name, output_dir / name)
        return {name: _sha256_text(content) for name, content in artifacts.items()}

    def render(self) -> dict[str, str]:
        """Render SDK artifacts without touching the filesystem."""

        records: list[dict[str, Any]] = []
        command_protocol_schema: dict[str, Any] | None = None
        for path in sorted(self.schema_paths):
            if not path.is_file():
                raise PackSdkError(f"schema does not exist: {path}")
            schema = json.loads(path.read_text(encoding="utf-8"))
            Draft202012Validator.check_schema(schema)
            schema_id = str(schema.get("$id") or path.name)
            if path.name == "command-protocol-v1.schema.json":
                command_protocol_schema = schema
            definitions = sorted(
                str(name)
                for name in (schema.get("$defs") or {}).keys()
            )
            records.append(
                {
                    "schema_id": schema_id,
                    "filename": path.name,
                    "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                    "definitions": definitions,
                }
            )
        index = {
            "generated": True,
            "generator": "tobkiri.core_runtime.pack_sdk/v1",
            "schemas": records,
        }
        index_text = json.dumps(
            index,
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        ) + "\n"
        python_lines = [
            '"""Generated by core_runtime.pack_sdk; do not edit."""',
            "",
            "from typing import Final",
            "",
            "SCHEMA_IDS: Final[dict[str, str]] = {",
        ]
        typescript_lines = [
            "// Generated by core_runtime.pack_sdk; do not edit.",
            "",
            "export const schemaIds = {",
        ]
        dart_lines = [
            "// Generated by core_runtime.pack_sdk; do not edit.",
            "",
            "const Map<String, String> packSchemaIds = <String, String>{",
        ]
        for record in records:
            symbol = _symbol(record["filename"])
            python_lines.append(
                f'    "{symbol}": {record["schema_id"]!r},'
            )
            typescript_lines.append(
                f'  {json.dumps(symbol)}: {json.dumps(record["schema_id"])},'
            )
            dart_lines.append(
                f"  {json.dumps(symbol)}: {json.dumps(record['schema_id'])},"
            )
        python_lines.extend(["}", ""])
        typescript_lines.extend(["} as const;", ""])
        dart_lines.extend(["};", ""])
        python_models = '''"""Generated command protocol DTOs; do not edit."""

from typing import Any, Literal, NotRequired, TypedDict

CommandMode = Literal["chat", "coding", "agent"]

class CommandInvocationRequest(TypedDict):
    command_ref: str
    args: dict[str, Any]
    invocation_id: str
    mode: CommandMode
    conversation_id: NotRequired[str]
    profile_id: NotRequired[str]
    catalog_revision: NotRequired[str]
    expected_revision: NotRequired[int]
    idempotency_key: NotRequired[str]
    client_sequence: NotRequired[int]
    approval_token: NotRequired[str]
    authority_request_id: NotRequired[str]
    authority_approval_token: NotRequired[str]

class CommandProtocolError(TypedDict):
    code: str
    message: str

class CommandInvocationResult(TypedDict):
    api_version: Literal["tobkiri.commands/v1"]
    operation_id: str
    status: Literal["succeeded", "failed", "approval_required", "cancelled"]
    command_ref: str
    state_changes: list[dict[str, Any]]
    error: NotRequired[CommandProtocolError]
'''
        typescript_models = """// Generated command protocol DTOs; do not edit.
export type CommandMode = "chat" | "coding" | "agent";
export interface CommandInvocationRequest {
  command_ref: string;
  args: Record<string, unknown>;
  invocation_id: string;
  mode: CommandMode;
  conversation_id?: string;
  profile_id?: string;
  catalog_revision?: string;
  expected_revision?: number;
  idempotency_key?: string;
  client_sequence?: number;
  approval_token?: string;
  authority_request_id?: string;
  authority_approval_token?: string;
}
export interface CommandProtocolError { code: string; message: string }
export interface CommandInvocationResult {
  api_version: "tobkiri.commands/v1";
  operation_id: string;
  status: "succeeded" | "failed" | "approval_required" | "cancelled";
  command_ref: string;
  state_changes: Array<Record<string, unknown>>;
  error?: CommandProtocolError;
}
"""
        dart_models = """// Generated command protocol DTOs; do not edit.
typedef JsonMap = Map<String, Object?>;
enum CommandMode { chat, coding, agent }
final class CommandInvocationRequest {
  const CommandInvocationRequest({
    required this.commandRef,
    required this.args,
    required this.invocationId,
    required this.mode,
    this.conversationId,
    this.profileId,
    this.catalogRevision,
    this.expectedRevision,
    this.idempotencyKey,
    this.clientSequence,
    this.approvalToken,
    this.authorityRequestId,
    this.authorityApprovalToken,
  });
  final String commandRef;
  final JsonMap args;
  final String invocationId;
  final CommandMode mode;
  final String? conversationId;
  final String? profileId;
  final String? catalogRevision;
  final int? expectedRevision;
  final String? idempotencyKey;
  final int? clientSequence;
  final String? approvalToken;
  final String? authorityRequestId;
  final String? authorityApprovalToken;
  JsonMap toJson() => <String, Object?>{
    'command_ref': commandRef, 'args': args, 'invocation_id': invocationId,
    'mode': mode.name, if (conversationId != null) 'conversation_id': conversationId,
    if (profileId != null) 'profile_id': profileId,
    if (catalogRevision != null) 'catalog_revision': catalogRevision,
    if (expectedRevision != null) 'expected_revision': expectedRevision,
    if (idempotencyKey != null) 'idempotency_key': idempotencyKey,
    if (clientSequence != null) 'client_sequence': clientSequence,
    if (approvalToken != null) 'approval_token': approvalToken,
    if (authorityRequestId != null) 'authority_request_id': authorityRequestId,
    if (authorityApprovalToken != null)
      'authority_approval_token': authorityApprovalToken,
  };
}
final class CommandProtocolError {
  const CommandProtocolError({required this.code, required this.message});
  final String code;
  final String message;
  factory CommandProtocolError.fromJson(JsonMap json) => CommandProtocolError(
    code: json['code'] as String? ?? 'UNKNOWN',
    message: json['message'] as String? ?? '',
  );
}
final class CommandInvocationResult {
  const CommandInvocationResult({
    required this.apiVersion,
    required this.operationId,
    required this.status,
    required this.commandRef,
    required this.stateChanges,
    this.error,
  });
  final String apiVersion;
  final String operationId;
  final String status;
  final String commandRef;
  final List<JsonMap> stateChanges;
  final CommandProtocolError? error;
  factory CommandInvocationResult.fromJson(JsonMap json) =>
      CommandInvocationResult(
        apiVersion: json['api_version'] as String? ?? '',
        operationId: json['operation_id'] as String? ?? '',
        status: json['status'] as String? ?? 'failed',
        commandRef: json['command_ref'] as String? ?? '',
        stateChanges: (json['state_changes'] as List<Object?>? ?? const [])
            .whereType<JsonMap>()
            .toList(growable: false),
        error: json['error'] is JsonMap
            ? CommandProtocolError.fromJson(json['error'] as JsonMap)
            : null,
      );
}
"""
        if command_protocol_schema is not None:
            python_models, typescript_models, dart_models = (
                _render_command_protocol_models(command_protocol_schema)
            )
        return {
            "contract_index.json": index_text,
            "contract_ids.py": "\n".join(python_lines),
            "contractIds.ts": "\n".join(typescript_lines),
            "contract_ids.dart": "\n".join(dart_lines),
            "command_protocol_models.py": python_models,
            "commandProtocolModels.ts": typescript_models,
            "command_protocol_models.dart": dart_models,
        }


def validate_pack_manifest(
    manifest_path: Path,
    *,
    schema_path: Path,
) -> dict[str, Any]:
    """Validate a Pack manifest with strict Draft 2020-12 semantics."""

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("pack_api_version") == "io.tobkiri.pack.v4":
        try:
            return validate_document(manifest, "pack")
        except ProtocolError as exc:
            raise PackSdkError(str(exc)) from exc
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    errors = sorted(
        validator.iter_errors(manifest),
        key=lambda item: tuple(str(part) for part in item.absolute_path),
    )
    if errors:
        first = errors[0]
        location = ".".join(str(part) for part in first.absolute_path) or "$"
        raise PackSdkError(f"{location}: {first.message}")
    return manifest


def scaffold_pack(
    target: Path,
    *,
    pack_id: str,
    display_name: str,
    profile: str = "complete",
    intent: str = "",
) -> Path:
    """Create an inert, untrusted Pack v4 with deterministic artifacts."""

    from core_runtime.pack_templates import (
        PackTemplateError,
        render_template_files,
        resolve_profile,
    )

    normalized_id = str(pack_id or "").strip()
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+", normalized_id):
        raise PackSdkError("pack_id must be a qualified lowercase identifier")
    target = Path(target)
    if target.is_symlink():
        raise PackSdkError("target directory must not be a symlink")
    if target.exists() and next(os.scandir(target), None) is not None:
        raise PackSdkError("target directory must be empty")
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.parent.is_symlink():
        raise PackSdkError("target parent must not be a symlink")
    try:
        selected_profile = resolve_profile(profile, intent)
        template_files = render_template_files(
            pack_id=normalized_id,
            display_name=str(display_name or normalized_id),
            profile=selected_profile,
            intent=intent,
        )
    except PackTemplateError as exc:
        raise PackSdkError(str(exc)) from exc
    template_files.pop("ecosystem.json", None)
    source = {
        "source_api_version": "io.tobkiri.pack-scaffold-source.v1",
        "pack_id": normalized_id,
        "version": "0.1.0",
        "display_name": str(display_name or normalized_id),
        "profile": selected_profile,
        "intent": str(intent or "")[:1000],
        "authority": "none",
    }
    with tempfile.TemporaryDirectory(prefix=".tobkiri-pack-", dir=target.parent) as value:
        staging = Path(value)
        (staging / "scaffold-source.v1.json").write_text(
            _json_text(source), encoding="utf-8"
        )
        for relative, content in sorted(template_files.items()):
            path = _scoped_scaffold_path(staging, relative)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        refresh_scaffold_artifacts(staging)
        if target.exists():
            target.rmdir()
        os.replace(staging, target)
    return target / "pack.v4.json"


_SCAFFOLD_GENERATED = frozenset(
    {
        "pack.v4.json",
        "contracts.v4.json",
        "artifact-index.v4.json",
        "executables.v4.json",
    }
)


def refresh_scaffold_artifacts(pack_root: Path) -> None:
    """Regenerate and validate all Pack v4 authority files for a scaffold."""

    root = Path(pack_root)
    source_path = root / "scaffold-source.v1.json"
    if root.is_symlink() or source_path.is_symlink() or not source_path.is_file():
        raise PackSdkError("scaffold-source.v1.json is required in a safe Pack root")
    source = json.loads(source_path.read_text(encoding="utf-8"))
    if not isinstance(source, dict) or source.get("source_api_version") != (
        "io.tobkiri.pack-scaffold-source.v1"
    ):
        raise PackSdkError("scaffold source is invalid")
    pack_id = str(source.get("pack_id") or "")
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+", pack_id):
        raise PackSdkError("scaffold source pack_id is invalid")
    artifacts: list[dict[str, str]] = []
    for path in _finite_scaffold_files(root):
        relative = path.relative_to(root).as_posix()
        if relative in _SCAFFOLD_GENERATED:
            continue
        artifacts.append(
            {
                "path": relative,
                "digest": "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest(),
                "kind": "sidecar" if relative == source_path.name else "asset",
            }
        )
    source_identity = canonical_digest(source)
    contracts = {
        "catalog_api_version": "io.tobkiri.pack-contract-catalog.v4",
        "pack_id": pack_id,
        "source_identity": source_identity,
        "contracts": [],
    }
    contract_text = _json_text(contracts)
    artifact_set_digest = canonical_digest(artifacts)
    provenance = {
        "schema": "io.tobkiri.provenance.v1",
        "source_kind": "generated",
        "source_path": source_path.name,
        "source_digest": source_identity,
        "repository_commit": "working-tree",
        "repository_tree": source_identity.removeprefix("sha256:"),
        "generator": "tobkiri.core_runtime.pack_sdk",
        "generator_version": "4.0.0",
        "normative": True,
        "evidence": [
            {
                "path": source_path.name,
                "rule_id": "canonical-pack-v4-scaffold-source",
                "digest": source_identity,
            }
        ],
    }
    manifest = {
        "pack_api_version": "io.tobkiri.pack.v4",
        "pack": {
            "id": pack_id,
            "version": str(source.get("version") or "0.1.0"),
            "kind": "normal_sandbox",
            "artifact_digest": artifact_set_digest,
            "display_name": str(source.get("display_name") or pack_id),
        },
        "functions": [],
        "contracts": [],
        "artifacts": artifacts,
        "requirements": {
            "pack_dependencies": {},
            "contract_dependencies": [],
            "capabilities": [],
            "network": {"allowed_domains": [], "allowed_ports": []},
            "secrets": [],
            "execution_boundary": "declarative_only",
            "approval_policy": "none",
            "workspace_boundary": "pack_local",
        },
        "operation_catalog": [],
        "provider_catalog": [],
        "integrity": {
            "source_identity": source_identity,
            "artifact_set_digest": artifact_set_digest,
            "contract_catalog_digest": "sha256:"
            + hashlib.sha256(contract_text.encode("utf-8")).hexdigest(),
        },
        "provenance": provenance,
        "migration": {
            "compatibility": "none",
            "legacy_ids": [],
            "removal_wave": 0,
            "sunset_at": "2026-08-05",
        },
    }
    manifest_text = _json_text(manifest)
    unsigned_index = {
        "index_api_version": "io.tobkiri.pack-artifact-index.v4",
        "pack_id": pack_id,
        "source_identity": source_identity,
        "artifacts": [
            {
                "path": "pack.v4.json",
                "digest": "sha256:"
                + hashlib.sha256(manifest_text.encode("utf-8")).hexdigest(),
                "role": "canonical_manifest",
            },
            {
                "path": "contracts.v4.json",
                "digest": "sha256:"
                + hashlib.sha256(contract_text.encode("utf-8")).hexdigest(),
                "role": "contract_catalog",
            },
            *[
                {"path": item["path"], "digest": item["digest"], "role": "sidecar"}
                for item in artifacts
            ],
        ],
        "artifact_set_digest": artifact_set_digest,
    }
    index = {
        **unsigned_index,
        "integrity_seal": {
            "algorithm": "sha256-canonical-v1",
            "signed_digest": canonical_digest(unsigned_index),
        },
    }
    unsigned_executables = {
        "catalog_api_version": "io.tobkiri.executable-catalog.v4",
        "pack_id": pack_id,
        "source_identity": source_identity,
        "variants": [],
    }
    executables = {
        **unsigned_executables,
        "catalog_digest": canonical_digest(unsigned_executables),
    }
    validate_document(manifest, "pack")
    validate_document(contracts, "pack_contract_catalog")
    validate_document(index, "pack_artifact_index")
    validate_document(executables, "executable_catalog")
    for name, document in (
        ("pack.v4.json", manifest),
        ("contracts.v4.json", contracts),
        ("artifact-index.v4.json", index),
        ("executables.v4.json", executables),
    ):
        path = root / name
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(_json_text(document), encoding="utf-8")
        os.replace(temporary, path)


def _scoped_scaffold_path(root: Path, relative: str) -> Path:
    path = root / relative
    resolved_root = root.resolve()
    resolved = path.resolve()
    if resolved_root != resolved and resolved_root not in resolved.parents:
        raise PackSdkError("template path escaped Pack root")
    return path


def _finite_scaffold_files(root: Path) -> tuple[Path, ...]:
    """Enumerate only descendants of one explicit scaffold boundary."""

    files: list[Path] = []
    pending = [root]
    while pending:
        current = pending.pop()
        for path in finite_children(current):
            if path.is_dir():
                pending.append(path)
            elif path.is_file():
                files.append(path)
    return tuple(sorted(files))


def _json_text(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def _symbol(filename: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", filename).strip("_").lower()


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _render_command_protocol_models(
    schema: dict[str, Any],
) -> tuple[str, str, str]:
    definitions = schema.get("$defs")
    definitions = definitions if isinstance(definitions, dict) else {}
    names = (
        "commandInvocationRequest",
        "commandProtocolError",
        "commandInvocationResult",
    )
    models: dict[str, dict[str, Any]] = {}
    for name in names:
        model = definitions.get(name)
        if isinstance(model, dict):
            models[name] = model
    if set(models) != set(names):
        raise PackSdkError(
            "command protocol schema is missing SDK model definitions"
        )
    mode_schema = models["commandInvocationRequest"]["properties"]["mode"]
    mode_values = _string_values(mode_schema, "command mode")

    python_lines = [
        '"""Generated from command-protocol-v1.schema.json; do not edit."""',
        "",
        "from typing import Any, Literal, NotRequired, TypedDict",
        "",
        f"CommandMode = Literal[{', '.join(repr(item) for item in mode_values)}]",
        "",
    ]
    typescript_lines = [
        "// Generated from command-protocol-v1.schema.json; do not edit.",
        f"export type CommandMode = {' | '.join(json.dumps(item) for item in mode_values)};",
    ]
    for name, model in models.items():
        class_name = _pascal_case(name)
        properties = model.get("properties")
        properties = properties if isinstance(properties, dict) else {}
        required = {str(item) for item in model.get("required") or []}
        python_lines.extend([f"class {class_name}(TypedDict):"])
        typescript_lines.append(f"export interface {class_name} {{")
        for field, field_schema in properties.items():
            if not isinstance(field_schema, dict):
                continue
            python_type = _python_schema_type(
                field_schema,
                field_name=str(field),
            )
            if field not in required:
                python_type = f"NotRequired[{python_type}]"
            python_lines.append(f"    {field}: {python_type}")
            optional = "" if field in required else "?"
            typescript_lines.append(
                f"  {field}{optional}: "
                f"{_typescript_schema_type(field_schema, field_name=str(field))};"
            )
        if not properties:
            python_lines.append("    pass")
        python_lines.append("")
        typescript_lines.extend(["}", ""])

    dart_lines = [
        "// Generated from command-protocol-v1.schema.json; do not edit.",
        "typedef JsonMap = Map<String, Object?>;",
        "",
        f"enum CommandMode {{ {', '.join(mode_values)} }}",
        "",
    ]
    for name, model in models.items():
        class_name = _pascal_case(name)
        properties = model.get("properties")
        properties = properties if isinstance(properties, dict) else {}
        required = {str(item) for item in model.get("required") or []}
        dart_lines.append(f"final class {class_name} {{")
        constructor_fields = [
            f"{'required ' if field in required else ''}"
            f"this.{_lower_camel(field)}"
            for field in properties
        ]
        compact_constructor = (
            f"  const {class_name}({{{', '.join(constructor_fields)}}});"
        )
        if len(compact_constructor) <= 80:
            dart_lines.append(compact_constructor)
        else:
            dart_lines.append(f"  const {class_name}({{")
            for field in properties:
                camel = _lower_camel(field)
                prefix = "required " if field in required else ""
                dart_lines.append(f"    {prefix}this.{camel},")
            dart_lines.append("  });")
        for field, field_schema in properties.items():
            if not isinstance(field_schema, dict):
                continue
            dart_type = _dart_schema_type(
                field_schema,
                field_name=str(field),
            )
            nullable = "" if field in required else "?"
            dart_lines.append(
                f"  final {dart_type}{nullable} {_lower_camel(field)};"
            )
        dart_lines.extend(
            _dart_serialization_lines(
                class_name,
                properties,
                required,
            )
        )
        dart_lines.extend(["}", ""])
    return (
        "\n".join(python_lines).rstrip() + "\n",
        "\n".join(typescript_lines).rstrip() + "\n",
        "\n".join(dart_lines).rstrip() + "\n",
    )


def _string_values(schema: dict[str, Any], label: str) -> list[str]:
    values = schema.get("enum")
    if (
        not isinstance(values, list)
        or not values
        or any(not isinstance(item, str) for item in values)
    ):
        raise PackSdkError(f"{label} must be a non-empty string enum")
    return [str(item) for item in values]


def _python_schema_type(schema: dict[str, Any], *, field_name: str) -> str:
    if "$ref" in schema:
        return _pascal_case(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return f"Literal[{schema['const']!r}]"
    if "enum" in schema:
        return (
            "CommandMode"
            if field_name == "mode"
            else f"Literal[{', '.join(repr(item) for item in schema['enum'])}]"
        )
    value_type = schema.get("type")
    if value_type == "string":
        return "str"
    if value_type == "integer":
        return "int"
    if value_type == "array":
        item = schema.get("items")
        item = item if isinstance(item, dict) else {}
        return f"list[{_python_schema_type(item, field_name=field_name)}]"
    if value_type == "object":
        return "dict[str, Any]"
    return "Any"


def _typescript_schema_type(schema: dict[str, Any], *, field_name: str) -> str:
    if "$ref" in schema:
        return _pascal_case(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return (
            "CommandMode"
            if field_name == "mode"
            else " | ".join(json.dumps(item) for item in schema["enum"])
        )
    value_type = schema.get("type")
    if value_type == "string":
        return "string"
    if value_type in {"integer", "number"}:
        return "number"
    if value_type == "array":
        item = schema.get("items")
        item = item if isinstance(item, dict) else {}
        return f"Array<{_typescript_schema_type(item, field_name=field_name)}>"
    if value_type == "object":
        return "Record<string, unknown>"
    return "unknown"


def _dart_schema_type(schema: dict[str, Any], *, field_name: str) -> str:
    if "$ref" in schema:
        return _pascal_case(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "enum" in schema and field_name == "mode":
        return "CommandMode"
    value_type = schema.get("type")
    if value_type == "string" or "const" in schema or "enum" in schema:
        return "String"
    if value_type == "integer":
        return "int"
    if value_type == "array":
        return "List<JsonMap>"
    if value_type == "object":
        return "JsonMap"
    return "Object"


def _dart_serialization_lines(
    class_name: str,
    properties: dict[str, Any],
    required: set[str],
) -> list[str]:
    entries: list[str] = []
    for field, schema in properties.items():
        camel = _lower_camel(field)
        if field == "mode":
            value = f"{camel}.name"
        elif isinstance(schema, dict) and "$ref" in schema:
            value = (
                f"{camel}.toJson()"
                if field in required
                else f"{camel}!.toJson()"
            )
        else:
            value = camel
        if field in required:
            entries.append(f"{json.dumps(field)}: {value}")
        else:
            entries.append(
                f"if ({camel} != null) {json.dumps(field)}: {value}"
            )
    compact = f"  JsonMap toJson() => <String, Object?>{{{', '.join(entries)}}};"
    if len(compact) <= 80:
        lines = [compact]
    else:
        lines = ["  JsonMap toJson() => <String, Object?>{"]
        for entry in entries:
            rendered = f"        {entry},"
            if len(rendered) <= 80 or not entry.startswith("if ("):
                lines.append(rendered)
                continue
            condition, value = entry.split(") ", 1)
            lines.extend(
                [
                    f"        {condition})",
                    f"          {value},",
                ]
            )
        lines.append("      };")
    if class_name != "CommandInvocationRequest":
        factory_prefix = f"  factory {class_name}.fromJson(JsonMap json) =>"
        constructor = f"{class_name}("
        if len(f"{factory_prefix} {constructor}") <= 80:
            lines.append(f"{factory_prefix} {constructor}")
            argument_indent = "        "
            closing = "      );"
        else:
            lines.extend([factory_prefix, f"      {constructor}"])
            argument_indent = "        "
            closing = "      );"
        for field, schema in properties.items():
            camel = _lower_camel(field)
            dart_type = _dart_schema_type(
                schema if isinstance(schema, dict) else {},
                field_name=field,
            )
            if dart_type == "String":
                expression = f"json[{json.dumps(field)}] as String?"
                if field in required:
                    expression += " ?? ''"
            elif dart_type == "int":
                expression = f"json[{json.dumps(field)}] as int?"
                if field in required:
                    expression += " ?? 0"
            elif dart_type == "JsonMap":
                expression = f"json[{json.dumps(field)}] as JsonMap?"
                if field in required:
                    expression += " ?? const <String, Object?>{}"
            elif dart_type == "List<JsonMap>":
                lines.extend(
                    [
                        f"{argument_indent}{camel}: "
                        f"(json[{json.dumps(field)}] as List<Object?>? ?? const [])",
                        f"{argument_indent}    .whereType<JsonMap>()",
                        f"{argument_indent}    .toList(growable: false),",
                    ]
                )
                continue
            else:
                lines.extend(
                    [
                        f"{argument_indent}{camel}: "
                        f"json[{json.dumps(field)}] is JsonMap",
                        f"{argument_indent}    ? {dart_type}.fromJson("
                        f"json[{json.dumps(field)}] as JsonMap)",
                        f"{argument_indent}    : null,",
                    ]
                )
                continue
            lines.append(f"{argument_indent}{camel}: {expression},")
        lines.append(closing)
    return lines


def _pascal_case(value: str) -> str:
    return "".join(
        part[:1].upper() + part[1:]
        for part in re.split(r"[^A-Za-z0-9]+|(?=[A-Z])", value)
        if part
    )


def _lower_camel(value: str) -> str:
    pascal = _pascal_case(value)
    return pascal[:1].lower() + pascal[1:]
