"""Public offline compilation of new Named Profile source releases."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import shutil
import stat
import tempfile
from typing import Any, Mapping, Sequence

from scripts.generate_profile_artifacts import ProfileCatalog, render
from tobkiri_host.artifact_compiler import compile_pack_root
from tobkiri_protocol.defaultspack_bundle_order import (
    canonical_defaultspack_bundle_entries,
)
from tobkiri_protocol.validation import validate_document

from .profile_pack_projection import ProjectionPackSource


class ProfileAuthoringError(ValueError):
    """A finite authoring input cannot produce a new Named Profile release."""


def build_named_profile(
    target: Path,
    *,
    template_bundle: Path,
    intent: Mapping[str, Any],
    additional_pack_roots: Sequence[Path] = (),
) -> Path:
    """Create a new finite bundle using the formal Profile compiler.

    The template's locked catalog inputs are captured and digest-verified.
    Additional Normal Packs are captured, compiled, and added by their exact
    public identities; duplicate identities are rejected. Pack projections
    must belong to the intent's selected closure and declared artifact bytes.
    This creates only an unbound source release, never admission, approval,
    authority, activation, a Shell binary, or code execution.
    """

    target = Path(target).absolute()
    _safe_ancestors(target)
    if target.exists():
        raise ProfileAuthoringError("target must be a new directory")
    captured_intent = validate_document(_json(intent), "profile_intent")
    template = Path(template_bundle).absolute()
    lock = json.loads(_read(template / "bundle.lock.json"))
    entries = canonical_defaultspack_bundle_entries(lock["entries"])
    profile_entries = [item for item in entries if item["kind"] == "profile"]
    if not profile_entries:
        raise ProfileAuthoringError("template has no Profile catalog entry")
    ProfileCatalog(template, template / profile_entries[0]["path"])
    files: dict[str, bytes] = {}
    for entry in entries:
        raw = _read(template / entry["path"])
        if _digest(raw) != entry["digest"]:
            raise ProfileAuthoringError("template bundle input digest changed")
        files[entry["path"]] = raw
    ids = {
        json.loads(files[item["path"]])["pack"]["id"] for item in entries if item["kind"] == "pack"
    }
    sources: dict[str, tuple[str, str]] = {}
    for supplied in additional_pack_roots:
        source = Path(supplied).absolute()
        _safe_ancestors(source)
        compiled = compile_pack_root(source)
        manifest = validate_document(_read(source / "pack.v4.json"), "pack")
        pack_id = compiled.artifact.pack_id
        if (
            pack_id in ids
            or manifest["pack"]["kind"] != "normal_sandbox"
            or any(value in pack_id for value in ("/", "\\"))
        ):
            raise ProfileAuthoringError("additional Pack identity is duplicate or unsupported")
        ids.add(pack_id)
        prefix = f"pack-resources/{pack_id}"
        paths = {"pack.v4.json", "contracts.v4.json", "artifact-index.v4.json"}
        paths.update(item["path"] for item in manifest["artifacts"])
        declared = {item["path"]: item["digest"] for item in manifest["artifacts"]}
        for relative in sorted(paths):
            _safe_relative(relative)
            raw = _read(source / relative)
            if relative in declared and _digest(raw) != declared[relative]:
                raise ProfileAuthoringError("additional Pack artifact bytes changed")
            files[f"{prefix}/{relative}"] = raw
        for kind, name, source_name in (
            ("pack", f"packs/{pack_id}.pack.v4.json", "pack.v4.json"),
            ("executable_catalog", f"packs/{pack_id}.executables.v4.json", "executables.v4.json"),
        ):
            if name in files:
                raise ProfileAuthoringError("additional Pack catalog path conflicts")
            raw = files[f"{prefix}/{source_name}"]
            files[name] = raw
            entries.append({"kind": kind, "path": name, "digest": _digest(raw)})
        sources[pack_id] = (manifest["pack"]["artifact_digest"], prefix)
    compatibility_name = "authored.profile.v5.json"
    if compatibility_name in files or any(
        json.loads(files[item["path"]]).get("profile_id") == captured_intent["profile_id"]
        for item in profile_entries
    ):
        raise ProfileAuthoringError("new Profile identity or output path conflicts")
    # The compiler owns this output. The zero placeholder is only a staging
    # lock entry; it is replaced with the generated bytes before publication.
    entries.append({"kind": "profile", "path": compatibility_name, "digest": "sha256:" + "0" * 64})
    files["bundle.lock.json"] = _json(
        {"schema": lock["schema"], "entries": canonical_defaultspack_bundle_entries(entries)}
    )
    files["authored.profile.intent.v1.json"] = _json(captured_intent)
    if len(files) > 4096 or sum(map(len, files.values())) > 512 * 1024 * 1024:
        raise ProfileAuthoringError("finite Profile source bundle exceeds authoring limits")
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".profile-authoring-", dir=target.parent) as temporary:
        stage = Path(temporary).resolve(strict=True)
        _write_files(stage, files)
        for pack_id, (_digest_pin, prefix) in sources.items():
            compiled = compile_pack_root(stage / prefix)
            if compiled.artifact.pack_id != pack_id:
                raise ProfileAuthoringError("captured Pack identity changed")
        _compile(stage, sources)
        target.mkdir()
        try:
            _write_files(target, files)
            _compile(target, sources)
        except BaseException:
            shutil.rmtree(target)
            raise
    return target


def _compile(root: Path, sources: Mapping[str, tuple[str, str]]) -> None:
    outputs = render(
        bundle_root=root,
        intent_path=root / "authored.profile.intent.v1.json",
        compatibility_path=root / "authored.profile.v5.json",
        lock_path=root / "authored.profile.lock.v5.json",
        provenance_path=root / "authored.release.provenance.json",
        projection_pack_sources={
            pack_id: ProjectionPackSource(digest, root / prefix)
            for pack_id, (digest, prefix) in sources.items()
        },
    )
    for path, raw in outputs.items():
        path.write_bytes(raw)


def _write_files(root: Path, files: Mapping[str, bytes]) -> None:
    for name, raw in sorted(files.items()):
        _safe_relative(name)
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(raw)


def _safe_relative(value: str) -> None:
    path = PurePosixPath(value)
    if (
        path.is_absolute()
        or path.as_posix() != value
        or not path.parts
        or any(part in {".", ".."} for part in path.parts)
        or "\\" in value
    ):
        raise ProfileAuthoringError("authoring artifact path is unsafe")


def _safe_ancestors(path: Path) -> None:
    for candidate in (path, *path.parents):
        if candidate.is_symlink() or ".." in candidate.parts:
            raise ProfileAuthoringError("authoring path contains a symlink or traversal")


def _read(path: Path) -> bytes:
    _safe_ancestors(path)
    descriptor = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    with os.fdopen(descriptor, "rb") as stream:
        before = os.fstat(stream.fileno())
        if not stat.S_ISREG(before.st_mode) or before.st_size > 64 * 1024 * 1024:
            raise ProfileAuthoringError("authoring input is not a bounded regular file")
        raw = stream.read(64 * 1024 * 1024 + 1)
        after = os.fstat(stream.fileno())
    current = path.stat(follow_symlinks=False)

    def identity(item: os.stat_result) -> tuple[int, int, int, int]:
        return (item.st_dev, item.st_ino, item.st_size, item.st_mtime_ns)

    if (
        identity(before) != identity(after)
        or identity(after) != identity(current)
        or len(raw) != before.st_size
    ):
        raise ProfileAuthoringError("authoring input changed during capture")
    return raw


def _digest(raw: bytes) -> str:
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def _json(document: Any) -> bytes:
    return (json.dumps(document, indent=2, ensure_ascii=False) + "\n").encode()
