"""Keep signed Pack UI commands registered and authorized on the Host panel."""

from __future__ import annotations

import json
import re
import tomllib
import unittest
from pathlib import Path


LAUNCHER_ROOT = Path(__file__).resolve().parents[2]
TAURI_ROOT = LAUNCHER_ROOT / "src-tauri"
SIGNED_PACK_COMMANDS = (
    "signed_pack_admission_status",
    "admit_signed_pack_from_folder",
    "onboard_signed_pack_from_folder",
)


class SignedPackLauncherPermissionsTests(unittest.TestCase):
    def test_signed_pack_panel_commands_have_matching_native_permissions(self) -> None:
        build_script = (TAURI_ROOT / "build.rs").read_text(encoding="utf-8")
        launcher = (TAURI_ROOT / "src/lib.rs").read_text(encoding="utf-8")
        panel = json.loads(
            (TAURI_ROOT / "capabilities/launcher-panel.json").read_text(
                encoding="utf-8"
            )
        )
        manifest_commands = build_script.split(
            "tauri_build::AppManifest::new().commands(&[", 1
        )[1].split("        ]),", 1)[0]
        handler_commands = launcher.split(
            ".invoke_handler(tauri::generate_handler![", 1
        )[1].split("        ])", 1)[0]
        declared = set(re.findall(r'"([a-z_]+)"', manifest_commands))
        registered = set(re.findall(r"\b([a-z_]+),", handler_commands))
        allowed = set(panel["permissions"])

        self.assertEqual(panel["windows"], ["main"])
        self.assertIn("http://127.0.0.1:8765/*", panel["remote"]["urls"])
        for command in SIGNED_PACK_COMMANDS:
            with self.subTest(command=command):
                permission = "allow-" + command.replace("_", "-")
                self.assertIn(command, declared)
                self.assertIn(command, registered)
                self.assertIn(permission, allowed)
                entries = tomllib.loads(
                    (TAURI_ROOT / "permissions/autogenerated" / f"{command}.toml")
                    .read_text(encoding="utf-8")
                )["permission"]
                self.assertEqual(entries[0]["identifier"], permission)
                self.assertEqual(entries[0]["commands"]["allow"], [command])
                self.assertEqual(
                    entries[1]["commands"]["deny"], [command]
                )


if __name__ == "__main__":
    unittest.main()
