import assert from "node:assert/strict";
import test from "node:test";
import { canonicalRequestQuery } from "../e2e/contractRequestMatcher";
import { defaultspackContractRoute, defaultspackContractUrl } from "../src/lib/api";
import { confirmedChatReferenceCatalog } from "../src/lib/chatReferenceCatalog";
import { buildHistoryChatReference, confirmResolvedHistoryReference, historyReferenceMention } from "../src/lib/historyReferences";
import { createHistoryReferenceFixture, HistoryReferenceFixtureError } from "./historyReferenceFixture";

const NOW = 1_700_000_000_000;
const requestBody = { references: [{ kind: "chat", id: "c-smoke" }] };
const candidate = buildHistoryChatReference({ id: "c-smoke", title: "Untrusted display label" }, "defaults")!;
const rejects = (run: () => unknown, status = 400) => assert.throws(run,
  (error) => error instanceof HistoryReferenceFixtureError && error.status === status);

test("finite catalog and resolution share exact owner identity, revisions, digest, and membership", () => {
  const fixture = createHistoryReferenceFixture(() => NOW);
  const resolved = fixture.resolve(requestBody);
  assert.deepEqual(fixture.list(new URLSearchParams("limit=100")), resolved);
  assert.deepEqual(resolved, {
    kind: "tobkiri.chat.reference.snapshot.v1", profile_id: "defaults",
    store_revision: 1, project_revision: 0, snapshot_time: NOW, expires_at: NOW + 600_000,
    references: [{ kind: "chat", id: "c-smoke", label: "Preview Calendar Chat", conversation_ids: ["c-smoke"],
      // Independently generated by tobkiri_protocol.canonical.canonical_digest.
      snapshot_digest: "sha256:b71f822d821469d99e6c18876fea51061e3b79d22af57e13b1538a50a9d576bb", member_count: 1, membership_complete: true }],
    next_cursor: null, truncated: false,
  });
  const confirmed = confirmResolvedHistoryReference(candidate, resolved, NOW)!;
  assert.ok(confirmed);
  assert.equal(confirmed.label, "Preview Calendar Chat");
  assert.equal(historyReferenceMention(confirmed).syntax, "@chat:c-smoke");
  assert.deepEqual(historyReferenceMention(confirmed).reference.memberIds, ["c-smoke"]);
});

test("current finite catalog passes production catalog validation and responses are detached", (context) => {
  context.mock.method(Date, "now", () => NOW);
  const fixture = createHistoryReferenceFixture();
  const first = fixture.list(new URLSearchParams());
  const catalog = confirmedChatReferenceCatalog(first, "defaults");
  assert.deepEqual(catalog.candidates.map(({ kind, id, profileId }) => ({ kind, id, profileId })),
    [{ kind: "chat", id: "c-smoke", profileId: "defaults" }]);
  first.references[0].conversation_ids.push("forged");
  first.references[0].label = "Forged";
  assert.deepEqual(fixture.resolve(requestBody).references[0].conversation_ids, ["c-smoke"]);
  assert.equal(fixture.resolve(requestBody).references[0].label, "Preview Calendar Chat");
});

test("finite list requires canonical pagination and rejects Profile injection and stale cursors", () => {
  const fixture = createHistoryReferenceFixture(() => NOW);
  for (const query of ["", "limit=1", "limit=100"]) assert.equal(fixture.list(new URLSearchParams(query)).references.length, 1);
  for (const query of ["limit=0", "limit=101", "limit=01", "limit=1.5", "limit=true", "limit=", "limit=-1",
    "limit=1&limit=2", "profile_id=other", "profile_id=defaults", "approved=true", "operation=list",
    "cursor=", "cursor=1:sha256:stale", "cursor=a&cursor=b", "member_ids=c-smoke"]) {
    rejects(() => fixture.list(new URLSearchParams(query)));
  }
  rejects(() => fixture.list({} as URLSearchParams));
});

test("finite resolver rejects malformed, duplicate, unbounded, and client-owned authority fields", () => {
  const fixture = createHistoryReferenceFixture(() => NOW);
  for (const payload of [null, true, "resolve", [], {}, { references: [] }, { references: requestBody },
    { ...requestBody, profile_id: "defaults" }, { ...requestBody, profile_id: "other" },
    { ...requestBody, operation: "resolve" }, { ...requestBody, approved: true },
    { references: [null] }, { references: [{ kind: "chat" }] }, { references: [{ kind: ["chat"], id: "c-smoke" }] },
    { references: [{ kind: "chat", id: "../c-smoke" }] }, { references: [{ kind: "chat", id: 7 }] },
    { references: [{ kind: "chat", id: "c-smoke", label: "Injected" }] },
    { references: [{ kind: "chat", id: "c-smoke", member_ids: ["forged"] }] },
    { references: [{ kind: "chat", id: "c-smoke", conversation_ids: ["forged"] }] },
    { references: [...requestBody.references, ...requestBody.references] },
    { references: Array.from({ length: 17 }, (_, index) => ({ kind: "chat", id: `c-${index}` })) }]) {
    rejects(() => fixture.resolve(payload));
  }
  assert.equal(fixture.resolve(requestBody).references[0].id, "c-smoke");
});

test("unknown chat and group owners never receive a synthesized successful resolution", () => {
  const fixture = createHistoryReferenceFixture(() => NOW);
  for (const references of [[{ kind: "chat", id: "missing" }], [{ kind: "group", id: "c-smoke" }],
    [{ kind: "group", id: "group-coding" }], [...requestBody.references, { kind: "chat", id: "missing" }]]) {
    rejects(() => fixture.resolve({ references }), 404);
  }
});

test("production confirmation rejects wrong Profile, stale snapshots, and malformed membership", (context) => {
  context.mock.method(Date, "now", () => NOW);
  const good = createHistoryReferenceFixture(() => NOW).resolve(requestBody);
  const row = good.references[0];
  for (const raw of [{ ...good, profile_id: "other" }, { ...good, store_revision: -1 },
    { ...good, project_revision: "0" }, { ...good, snapshot_time: NOW + 60_001 },
    { ...good, expires_at: NOW }, { ...good, expires_at: NOW + 600_001 },
    { ...good, verified: true }, { ...good, next_cursor: "more", truncated: true },
    { ...good, references: [{ ...row, id: "missing" }] },
    { ...good, references: [{ ...row, snapshot_digest: "sha256:malformed" }] },
    { ...good, references: [{ ...row, conversation_ids: ["another-owner"] }] },
    { ...good, references: [{ ...row, conversation_ids: ["c-smoke", "c-smoke"], member_count: 2 }] },
    { ...good, references: [{ ...row, member_count: 0 }] },
    { ...good, references: [{ ...row, membership_complete: false }] }]) {
    assert.equal(confirmResolvedHistoryReference(candidate, raw, NOW), null);
  }
  assert.equal(confirmResolvedHistoryReference(candidate, good, NOW + 600_000), null);
  assert.deepEqual(confirmedChatReferenceCatalog(good, "other").candidates, []);
  assert.deepEqual(confirmedChatReferenceCatalog({ ...good, expires_at: NOW }, "defaults").candidates, []);
});

test("fixture clock is bounded and each request receives a fresh snapshot", () => {
  let now = NOW;
  const fixture = createHistoryReferenceFixture(() => now);
  const old = fixture.resolve(requestBody);
  now += 600_000;
  const current = fixture.resolve(requestBody);
  assert.equal(confirmResolvedHistoryReference(candidate, old, now), null);
  assert.ok(confirmResolvedHistoryReference(candidate, current, now));
  for (const clock of [-1, Number.NaN, Number.POSITIVE_INFINITY, 1.5, Number.MAX_SAFE_INTEGER]) {
    rejects(() => createHistoryReferenceFixture(() => clock).resolve(requestBody));
  }
});

test("reference routes use canonical method-bound transport before the fixture receives a request", () => {
  for (const [path, method] of [["api/chat/references", "GET"], ["api/chat/references/resolve", "POST"]]) {
    const target = defaultspackContractUrl(defaultspackContractRoute(path), method);
    const query = canonicalRequestQuery({ url: () => target, method: () => method }, path, method);
    assert.ok(query);
    assert.equal(canonicalRequestQuery({ url: () => `/${path}`, method: () => method }, path, method), null);
    assert.equal(canonicalRequestQuery({ url: () => target, method: () => "DELETE" }, path, method), null);
    assert.equal(canonicalRequestQuery({ url: () => target + "%ZZ", method: () => method }, path, method), null);
  }
});
