from __future__ import annotations

from typing import Any

from domain.tool.schema_adapter import provider_tool_parameters


REQUESTED_AGENT_OS_TOOL_IDS = [
    "artifact_file_read",
    "artifact_file_write",
    "artifact_file_patch",
    "artifact_file_delete",
    "artifact_file_list",
    "artifact_zip",
    "artifact_export",
    "html_preview",
    "artifact_preview",
    "image_render",
    "pdf_preview",
    "sheet_create",
    "sheet_read",
    "sheet_update",
    "sheet_analyze",
    "chart_create",
    "slides_create",
    "slides_update",
    "slides_from_markdown",
    "doc_create",
    "doc_update",
    "doc_to_pdf",
    "wide_research",
    "source_extract",
    "source_rank",
    "research_report_export",
    "job_create",
    "job_status",
    "job_cancel",
    "job_resume",
    "job_artifacts",
    "job_history",
    "sandbox_exec",
    "sandbox_files_read",
    "sandbox_files_apply_patch",
    "sandbox_port_expose",
    "python_exec",
    "node_exec",
    "package_install_plan",
    "desktop_list",
    "desktop_create",
    "desktop_frame",
    "desktop_frame_evidence",
    "desktop_input",
    "desktop_control_acquire",
    "desktop_control_renew",
    "desktop_control_release",
    "desktop_rules_update",
    "desktop_access_request",
    "desktop_access_grant",
    "project_scaffold",
    "webapp_build",
    "webapp_preview",
    "webapp_lint",
    "static_site_export",
    "webapp_export_static",
    "workflow_define",
    "workflow_run",
    "workflow_status",
    "workflow_retry",
    "workflow_cancel",
    "browser_download_collect",
    "browser_upload_file",
    "browser_save_page",
    "browser_extract_table",
    "pdf_extract",
    "pdf_extract_tables",
    "ocr_extract",
    "image_convert",
    "image_resize",
    "image_generate_local_or_provider",
    "audio_transcribe",
    "audio_transcribe_local",
    "tts_generate",
    "tts_generate_local",
    "doc_export",
    "slides_export",
    "sheet_export",
    "pdf_export",
    "github_search",
    "github_pr_create",
    "github_issue_create",
    "github_issue_update",
    "github_issue_list",
    "linear_issue_sync",
    "jira_issue_sync",
    "gmail_search",
    "gmail_draft",
    "calendar_create",
    "drive_create",
    "drive_export",
    "slack_send",
    "discord_send",
    "line_push",
]


def provider_tool_schema(tool_def: dict[str, Any]) -> dict[str, Any]:
    schema_value = tool_def.get("schema")
    schema: dict[str, Any] = schema_value if isinstance(schema_value, dict) else {}
    schema_parameters = schema.get("parameters")
    parameters = schema_parameters if isinstance(schema_parameters, dict) else schema
    return {
        "type": "function",
        "function": {
            "name": str(tool_def.get("tool_id") or tool_def.get("name") or ""),
            "description": str(tool_def.get("summary") or ""),
            "parameters": provider_tool_parameters(parameters),
        },
    }
