import 'dart:convert';
import 'dart:io';

void main() {
  final functionsDir =
      Directory('../tobkiri_runtime/ecosystem/defaultspack/functions').absolute;
  final toolsDir =
      Directory('../tobkiri_runtime/ecosystem/defaultspack/tools').absolute;
  if (!functionsDir.existsSync()) {
    stderr.writeln('defaultspack functions directory not found: $functionsDir');
    exitCode = 1;
    return;
  }
  if (!toolsDir.existsSync()) {
    stderr.writeln('defaultspack tools directory not found: $toolsDir');
    exitCode = 1;
    return;
  }

  final entriesById = <String, _ManifestEntry>{};
  void addEntry(_ManifestEntry entry) {
    entriesById[entry.id] = entriesById[entry.id]?.merge(entry) ?? entry;
  }

  for (final file in functionsDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('/manifest.json'))) {
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map) continue;
    final manifest = decoded.map((key, value) => MapEntry('$key', value));
    final tags = _stringList(manifest['tags']).toSet();
    if (!tags.contains('tool') && !tags.contains('agent')) continue;
    final id = _string(manifest['function_id']);
    if (id == null) continue;
    addEntry(
      _ManifestEntry(
        id: id,
        description: _string(manifest['description']) ?? '',
        tags: tags.toList()..sort(),
        aliases: _stringList(manifest['vocab_aliases'])..sort(),
        inputSchema: _map(manifest['input_schema']).isEmpty
            ? const {'type': 'object', 'additionalProperties': true}
            : _map(manifest['input_schema']),
      ),
    );
  }

  for (final file in toolsDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((file) => file.path.endsWith('/manifest.json'))) {
    final decoded = jsonDecode(file.readAsStringSync());
    if (decoded is! Map) continue;
    final manifest = decoded.map((key, value) => MapEntry('$key', value));
    final config = _map(manifest['config']);
    final id = _string(config['tool_id']) ?? _string(manifest['id']);
    if (id == null) continue;
    final schema = _map(config['schema']);
    final parameters = _map(schema['parameters']);
    final tags = <String>{
      'tool_registry',
      ..._stringList(config['tags']),
    };
    if (config['requires_approval'] == true) tags.add('requires_approval');
    final category = _string(config['tool_category']);
    if (category != null) tags.add(category);
    addEntry(
      _ManifestEntry(
        id: id,
        description: _string(config['summary']) ??
            _string(manifest['description']) ??
            '',
        tags: tags.toList()..sort(),
        aliases: const [],
        inputSchema: parameters.isEmpty
            ? const {'type': 'object', 'additionalProperties': true}
            : parameters,
      ),
    );
  }

  final entries = entriesById.values.toList()
    ..sort((a, b) => a.id.compareTo(b.id));
  final outFile =
      File('lib/src/data/local/defaultspack_tool_agent_manifest.g.dart');
  outFile.writeAsStringSync(_render(entries));
  final format = Process.runSync(Platform.resolvedExecutable, [
    'format',
    outFile.path,
  ]);
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exitCode = format.exitCode;
  }
}

String _render(List<_ManifestEntry> entries) {
  final buffer = StringBuffer()
    ..writeln(
        '// Generated by tool/generate_defaultspack_mobile_tool_manifest.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln('class DefaultspackToolAgentManifestEntry {')
    ..writeln('  const DefaultspackToolAgentManifestEntry({')
    ..writeln('    required this.id,')
    ..writeln('    required this.description,')
    ..writeln('    required this.tags,')
    ..writeln('    required this.aliases,')
    ..writeln('    required this.inputSchema,')
    ..writeln('  });')
    ..writeln()
    ..writeln('  final String id;')
    ..writeln('  final String description;')
    ..writeln('  final List<String> tags;')
    ..writeln('  final List<String> aliases;')
    ..writeln('  final Map<String, dynamic> inputSchema;')
    ..writeln('}')
    ..writeln()
    ..writeln('const defaultspackToolAgentManifestCatalog =')
    ..writeln('    <DefaultspackToolAgentManifestEntry>[');

  for (final entry in entries) {
    buffer
      ..writeln('  DefaultspackToolAgentManifestEntry(')
      ..writeln("    id: ${_dartString(entry.id)},")
      ..writeln("    description: ${_dartString(entry.description)},")
      ..writeln('    tags: ${_dartStringList(entry.tags)},')
      ..writeln('    aliases: ${_dartStringList(entry.aliases)},')
      ..writeln('    inputSchema: ${_dartLiteral(entry.inputSchema)},')
      ..writeln('  ),');
  }

  buffer.writeln('];');
  return buffer.toString();
}

String? _string(Object? value) {
  if (value == null) return null;
  final text = value.toString().trim();
  return text.isEmpty ? null : text;
}

List<String> _stringList(Object? value) {
  if (value is! List) return const [];
  return value
      .map((item) => item.toString().trim())
      .where((item) => item.isNotEmpty)
      .toList();
}

Map<String, dynamic> _map(Object? value) {
  if (value is! Map) return const {};
  return value.map((key, value) => MapEntry('$key', value));
}

String _dartString(String value) => jsonEncode(value).replaceAll(r'$', r'\$');

String _dartStringList(List<String> values) {
  return '<String>[${values.map(_dartString).join(', ')}]';
}

String _dartLiteral(Object? value) {
  if (value is Map) {
    final entries = value.entries.map((entry) {
      return '${_dartString('${entry.key}')}: ${_dartLiteral(entry.value)}';
    }).join(', ');
    return '<String, dynamic>{$entries}';
  }
  if (value is List) {
    return '<dynamic>[${value.map(_dartLiteral).join(', ')}]';
  }
  if (value is String) return _dartString(value);
  if (value is num || value is bool) return '$value';
  if (value == null) return 'null';
  return _dartString('$value');
}

class _ManifestEntry {
  const _ManifestEntry({
    required this.id,
    required this.description,
    required this.tags,
    required this.aliases,
    required this.inputSchema,
  });

  final String id;
  final String description;
  final List<String> tags;
  final List<String> aliases;
  final Map<String, dynamic> inputSchema;

  _ManifestEntry merge(_ManifestEntry other) {
    return _ManifestEntry(
      id: id,
      description:
          other.description.isNotEmpty ? other.description : description,
      tags: {...tags, ...other.tags}.toList()..sort(),
      aliases: {...aliases, ...other.aliases}.toList()..sort(),
      inputSchema:
          other.inputSchema.isNotEmpty ? other.inputSchema : inputSchema,
    );
  }
}
