import 'dart:convert';
import 'dart:io';

const _fallbackBaseUrls = <String, String>{
  'anthropic': 'https://api.anthropic.com',
  'deepseek': 'https://api.deepseek.com/v1',
  'google': 'https://generativelanguage.googleapis.com/v1beta/openai',
  'gemini': 'https://generativelanguage.googleapis.com/v1beta/openai',
  'openai': 'https://api.openai.com/v1',
  'openrouter': 'https://openrouter.ai/api/v1',
};

const _fallbackCompatibility = <String, String>{
  'anthropic': 'anthropic_messages',
  'deepseek': 'openai',
  'google': 'openai',
  'gemini': 'openai',
  'openai': 'openai',
  'openrouter': 'openai',
  'opencode-zen': 'anthropic_messages',
};

void main() {
  final providersDir =
      Directory('../tobkiri_runtime/ecosystem/defaultspack/domain/providers')
          .absolute
          .normalize();
  if (!providersDir.existsSync()) {
    stderr.writeln('defaultspack provider directory not found: $providersDir');
    exitCode = 1;
    return;
  }

  final configs = <_ProviderConfig>[];
  for (final entry in providersDir.listSync().whereType<Directory>()) {
    final manifestFile = File('${entry.path}/manifest.json');
    if (!manifestFile.existsSync()) continue;
    final manifest =
        jsonDecode(manifestFile.readAsStringSync()) as Map<String, dynamic>;
    final metadata = _map(manifest['provider_metadata']);
    final providerManifest = _map(manifest['provider_manifest']);
    final capabilities = _map(manifest['capabilities']);
    final providerId = _string(manifest['provider_id']) ??
        _string(providerManifest['id']) ??
        _string(manifest['id']) ??
        entry.uri.pathSegments.where((s) => s.isNotEmpty).last;
    final displayName = _string(manifest['display_name']) ??
        _string(metadata['display_name']) ??
        _string(providerManifest['display_name']) ??
        providerId;
    final kind = _string(metadata['kind']) ??
        _string(providerManifest['kind']) ??
        _string(manifest['kind']) ??
        'cloud';
    final catalogOnly = _bool(metadata['catalog_only']) ??
        _bool(providerManifest['catalog_only']) ??
        false;
    final local = kind == 'local' || _bool(capabilities['local']) == true;
    final defaultModel = _string(metadata['default_model']) ??
        _string(providerManifest['default_model']) ??
        '';
    final defaultBaseUrl = _string(metadata['default_base_url']) ??
        _string(providerManifest['default_base_url']) ??
        _fallbackBaseUrls[providerId] ??
        '';
    final apiCompatibility = _apiCompatibility(
      providerId: providerId,
      capabilities: capabilities,
      metadata: metadata,
      providerManifest: providerManifest,
    );
    final openaiCompatible = apiCompatibility == 'openai';
    configs.add(
      _ProviderConfig(
        providerId: providerId,
        displayName: displayName,
        baseUrl: defaultBaseUrl,
        model: defaultModel,
        openaiCompatible: openaiCompatible,
        local: local,
        catalogOnly: catalogOnly,
        apiCompatibility: apiCompatibility,
      ),
    );
  }

  configs.sort((a, b) => a.displayName.compareTo(b.displayName));
  final outFile = File('lib/src/settings/defaultspack_mobile_providers.g.dart');
  outFile.writeAsStringSync(_render(configs));
}

String _apiCompatibility({
  required String providerId,
  required Map<String, dynamic> capabilities,
  required Map<String, dynamic> metadata,
  required Map<String, dynamic> providerManifest,
}) {
  final config = _map(providerManifest['config']);
  final declared =
      (_string(config['api_compatibility']) ?? '').trim().toLowerCase();
  if (declared.contains('anthropic')) return 'anthropic_messages';
  if (declared.startsWith('openai')) return 'openai';
  final capabilityNames = [
    ...capabilities.entries
        .where((entry) => entry.value == true)
        .map((entry) => entry.key),
    ..._stringList(metadata['capabilities']),
  ].map((value) => value.toLowerCase()).toSet();
  if (capabilityNames.contains('anthropic_compatible')) {
    return 'anthropic_messages';
  }
  if (capabilityNames.contains('openai_compatible') ||
      capabilityNames.contains('openai_compatible_if_confirmed')) {
    return 'openai';
  }
  return _fallbackCompatibility[providerId] ?? 'unsupported';
}

String _render(List<_ProviderConfig> configs) {
  final buffer = StringBuffer()
    ..writeln(
        '// Generated by tool/generate_defaultspack_mobile_providers.dart.')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln("import 'api_config_store.dart';")
    ..writeln()
    ..writeln(
        'const defaultspackMobileProviderConfigs = <MobileProviderConfig>[');
  for (final config in configs) {
    buffer
      ..writeln('  MobileProviderConfig(')
      ..writeln("    providerId: ${_dartString(config.providerId)},")
      ..writeln("    displayName: ${_dartString(config.displayName)},")
      ..writeln("    label: '',")
      ..writeln("    apiKey: '',")
      ..writeln("    baseUrl: ${_dartString(config.baseUrl)},")
      ..writeln("    model: ${_dartString(config.model)},")
      ..writeln('    openaiCompatible: ${config.openaiCompatible},')
      ..writeln('    local: ${config.local},')
      ..writeln('    catalogOnly: ${config.catalogOnly},')
      ..writeln(
          "    apiCompatibility: ${_dartString(config.apiCompatibility)},")
      ..writeln('  ),');
  }
  buffer.writeln('];');
  return buffer.toString();
}

Map<String, dynamic> _map(Object? value) {
  if (value is Map) {
    return value.map((key, value) => MapEntry(key.toString(), value));
  }
  return const {};
}

String? _string(Object? value) {
  if (value == null) return null;
  final text = value.toString().trim();
  return text.isEmpty ? null : text;
}

bool? _bool(Object? value) => value is bool ? value : null;

List<String> _stringList(Object? value) {
  if (value is! List) return const [];
  return value.map((item) => item.toString()).toList();
}

String _dartString(String value) => jsonEncode(value);

class _ProviderConfig {
  const _ProviderConfig({
    required this.providerId,
    required this.displayName,
    required this.baseUrl,
    required this.model,
    required this.openaiCompatible,
    required this.local,
    required this.catalogOnly,
    required this.apiCompatibility,
  });

  final String providerId;
  final String displayName;
  final String baseUrl;
  final String model;
  final bool openaiCompatible;
  final bool local;
  final bool catalogOnly;
  final String apiCompatibility;
}

extension on Directory {
  Directory normalize() {
    return Directory(resolveSymbolicLinksSync());
  }
}
